---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: Talvez seja necessário substituir o controlador SG6000-CN se ele não estiver funcionando de forma ideal ou se ele tiver falhado. 
---
= Substitua o controlador SG6000-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário substituir o controlador SG6000-CN se ele não estiver funcionando de forma ideal ou se ele tiver falhado.

.O que você vai precisar
* Você tem um controlador de substituição com o mesmo número de peça do controlador que está substituindo.
* Você tem etiquetas para identificar cada cabo conetado ao controlador.
* Você localizou fisicamente o controlador para substituir no data center.
+
xref:locating-controller-in-data-center.adoc[Localize o controlador no data center]



.Sobre esta tarefa
O nó de armazenamento do aparelho não estará acessível quando substituir o controlador SG6000-CN. Se o controlador SG6000-CN estiver a funcionar o suficiente, pode efetuar um encerramento controlado no início deste procedimento.


NOTE: Se você estiver substituindo o controlador antes de instalar o software StorageGRID, talvez você não consiga acessar o instalador do StorageGRID Appliance imediatamente após concluir este procedimento. Embora você possa acessar o Instalador de dispositivos StorageGRID de outros hosts na mesma sub-rede que o appliance, você não pode acessá-lo de hosts em outras sub-redes. Esta condição deve resolver-se dentro de 15 minutos (quando qualquer entrada de cache ARP para o tempo limite do controlador original), ou você pode limpar a condição imediatamente, limpando quaisquer entradas de cache ARP antigas manualmente do roteador ou gateway local.

.Passos
. Apresente as configurações atuais do aparelho e registe-as.
+
.. Inicie sessão no aparelho a substituir:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



.. Enter: `*run-host-command ipmitool lan print*` Para exibir as configurações atuais do BMC para o dispositivo.


. Se o controlador SG6000-CN estiver a funcionar o suficiente para permitir um encerramento controlado, desligue o controlador SG6000-CN.
+
xref:shutting-down-sg6000-cn-controller.adoc[Desligue o controlador SG6000-CN]

. Se qualquer uma das interfaces de rede neste dispositivo StorageGRID estiver configurada para DHCP, talvez seja necessário atualizar as atribuições permanentes de concessão DHCP nos servidores DHCP para fazer referência aos endereços MAC do dispositivo de substituição. A atualização garante que o dispositivo recebe os endereços IP esperados.
+
.. Localize a etiqueta de endereço MAC na parte frontal do controlador SG6000-CN e determine o endereço MAC da porta Admin Network.
+
[NOTE]
====
O rótulo de endereço MAC lista o endereço MAC da porta de gerenciamento BMC.

Para determinar o endereço MAC da porta Admin Network, você deve adicionar *2* ao número hexadecimal na etiqueta. Por exemplo, se o endereço MAC na etiqueta terminar em *09*, o endereço MAC da porta Admin terminaria em *0B*. Se o endereço MAC na etiqueta terminar em *(_y_)FF*, o endereço MAC da porta Admin terminaria em *(_y_(1)01*. Você pode facilmente fazer esse cálculo abrindo o Calculator no Windows, definindo-o para o modo Programador, selecionando Hex, digitando o endereço MAC e, em seguida, digitando * 2 *.

====
.. Peça ao administrador da rede para associar o DNS/rede e o endereço IP do controlador removido com o endereço MAC do controlador de substituição.
+

IMPORTANT: Você deve garantir que todos os endereços IP do controlador original foram atualizados antes de aplicar energia ao controlador de substituição. Caso contrário, o controlador obterá novos endereços IP DHCP quando iniciar e poderá não conseguir reconetar-se ao StorageGRID. Esta etapa se aplica a todas as redes StorageGRID conetadas ao controlador.

+

NOTE: Se o controlador original usou o endereço IP estático, o novo controlador adotará automaticamente os endereços IP do controlador que você removeu.



. Retirar e substituir o controlador SG6000-CN:
+
.. Identifique os cabos e, em seguida, desconete os cabos e quaisquer transcetores SFP ou SFP28.
+

IMPORTANT: Para evitar um desempenho degradado, não torça, dobre, aperte ou pise nos cabos.

.. Remova o controlador com falha do gabinete ou rack.
.. Instale o controlador de substituição no gabinete ou rack.
.. Substitua os cabos e quaisquer transcetores SFP ou SFP28.
.. Ligue o controlador e monitorize os LEDs do controlador e os códigos de arranque.


. Se o dispositivo em que você substituiu o controlador usou um servidor de gerenciamento de chaves (KMS) para criptografar dados, poderá ser necessária uma configuração adicional antes que o nó possa ingressar na grade. Se o nó não ingressar automaticamente na grade, verifique se essas configurações foram transferidas para o novo controlador e configure manualmente quaisquer configurações que não tenham a configuração esperada:
+
** link:../sg6000/configuring-storagegrid-connections.html["Configurar conexões StorageGRID"]
** link:../admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["Configure a criptografia de nó para o dispositivo"]


. Inicie sessão no aparelho com o controlador substituído:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


. Restaure a conetividade de rede BMC para o dispositivo. Existem duas opções:
+
** Use IP estático, máscara de rede e gateway
** Use DHCP para obter um IP, máscara de rede e gateway
+
... Para restaurar a configuração do BMC para usar um IP estático, máscara de rede e gateway, digite os seguintes comandos:
+
`*run-host-command ipmitool lan set 1 ipsrc static*`

+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... Para restaurar a configuração do BMC para usar DHCP para obter um IP, máscara de rede e gateway, digite o seguinte comando:
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. Depois de restaurar a conetividade de rede BMC, conete-se à interface BMC para auditar e restaurar qualquer configuração personalizada adicional do BMC que você possa ter aplicado. Por exemplo, você deve confirmar as configurações para destinos de intercetação SNMP e notificações por e-mail. link:configuring-bmc-interface-sg6000.html["Configurar a interface BMC"]Consulte .
. Confirme se o nó do dispositivo é exibido no Gerenciador de Grade e se nenhum alerta é exibido.


.Informações relacionadas
xref:sg6000-cn-installing-into-cabinet-or-rack.adoc[SG6000-CN: Instalar no armário ou no rack]

xref:viewing-status-indicators-and-buttons-on-sg6000-cn-controller.adoc[Visualizar indicadores de status e botões no controlador SG6000-CN]

xref:viewing-boot-up-codes-for-sg6000-cn-controller.adoc[Veja os códigos de inicialização para o controlador SG6000-CN]
