---
permalink: sg6000/unable-to-connect-to-appliance.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, troubleshoot, troubleshooting, connect, connection, unable to connect, no connection 
summary: Se não conseguir ligar ao dispositivo, poderá haver um problema de rede ou a instalação do hardware poderá não ter sido concluída com êxito. 
---
= Não foi possível ligar ao aparelho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se não conseguir ligar ao dispositivo, poderá haver um problema de rede ou a instalação do hardware poderá não ter sido concluída com êxito.

.Passos
. Se você não conseguir se conetar ao Gerenciador do sistema do SANtricity:
+
.. Tente fazer ping no dispositivo usando o endereço IP para qualquer controlador de armazenamento na rede de gerenciamento para o Gerenciador de sistema SANtricity
`*ping _Storage_Controller_IP_*`
.. Se não receber resposta do ping, confirme que está a utilizar o endereço IP correto.
+
Use o endereço IP para a porta de gerenciamento 1 em qualquer controlador de armazenamento.

.. Se o endereço IP estiver correto, verifique o cabeamento do dispositivo e a configuração da rede.
+
Se isso não resolver o problema, entre em Contato com o suporte técnico.

.. Se o ping foi bem-sucedido, abra um navegador da Web.
.. Digite o URL para o Gerenciador de sistema do SANtricity
`*https://_Storage_Controller_IP_*`
+
É apresentada a página de início de sessão do Gestor do sistema SANtricity.



. Se não conseguir ligar ao controlador SG6000-CN:
+
.. Tente fazer ping no aparelho usando o endereço IP do controlador SG6000-CN
`*ping _SG6000-CN_Controller_IP_*`
.. Se não receber resposta do ping, confirme que está a utilizar o endereço IP correto.
+
Pode utilizar o endereço IP do dispositivo na rede de grelha, na rede de administração ou na rede de cliente.

.. Se o endereço IP estiver correto, verifique o cabeamento do dispositivo, os transcetores SFP e a configuração da rede.
.. Se o acesso físico ao SG6000-CN estiver disponível, você pode usar uma conexão direta com o IP local de link permanente `169.254.0.1` para verificar a configuração de rede do controlador e atualizar, se necessário. Para obter instruções detalhadas, consulte o passo 2 em xref:..//sg6000/accessing-storagegrid-appliance-installer-sg6000.adoc[Acessando o Instalador de dispositivos StorageGRID].
+
Se isso não resolver o problema, entre em Contato com o suporte técnico.

.. Se o ping foi bem-sucedido, abra um navegador da Web.
.. Digite o URL do instalador do StorageGRID Appliance
`*https://_SG6000-CN_Controller_IP_:8443*`
+
A página inicial é exibida.




