---
permalink: sg6000/upgrading-santricity-os-on-storage-controllers.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Para garantir o funcionamento ideal do controlador de storage, é necessário atualizar para a versão de manutenção mais recente do SANtricity os qualificado para o seu dispositivo StorageGRID. Consulte a ferramenta de Matriz de interoperabilidade do NetApp (IMT) para determinar qual versão você deve usar. Se você precisar de assistência, entre em Contato com o suporte técnico.' 
---
= Atualizar o SANtricity os em controladores de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantir o funcionamento ideal do controlador de storage, é necessário atualizar para a versão de manutenção mais recente do SANtricity os qualificado para o seu dispositivo StorageGRID. Consulte a ferramenta de Matriz de interoperabilidade do NetApp (IMT) para determinar qual versão você deve usar. Se você precisar de assistência, entre em Contato com o suporte técnico.

Use um dos seguintes procedimentos com base na versão do SANtricity os atualmente instalado:

* Se o controlador de armazenamento estiver usando o SANtricity os 08.42.20.00 (11,42) ou mais recente, use o Gerenciador de Grade para executar a atualização.
+
xref:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6000.adoc[Atualize o SANtricity os em controladores de storage usando o Gerenciador de Grade]

* Se a controladora de storage estiver usando uma versão do SANtricity os anterior a 08.42.20.00 (11,42), use o modo de manutenção para executar a atualização.
+
xref:upgrading-santricity-os-on-storage-controllers-using-maintenance-mode-sg6000.adoc[Atualizar o SANtricity os em controladores de storage usando o modo de manutenção]




IMPORTANT: Ao atualizar o SANtricity os para o seu dispositivo de armazenamento, você deve seguir as instruções na documentação do StorageGRID. Se utilizar quaisquer outras instruções, o aparelho pode ficar inoperável.

.Informações relacionadas
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]

https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Downloads do NetApp: StorageGRID Appliance"^]

xref:../monitor/index.adoc[Monitorar e solucionar problemas]
