---
permalink: audit/client-write-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3, swift 
summary: As mensagens de auditoria de gravação do cliente são registradas quando um aplicativo cliente S3 ou Swift faz uma solicitação para criar ou modificar um objeto. 
---
= O cliente escreve mensagens de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria de gravação do cliente são registradas quando um aplicativo cliente S3 ou Swift faz uma solicitação para criar ou modificar um objeto.

|===
| Código | Descrição | Usado por | Consulte 


 a| 
OVWR
 a| 
Object Overwrite: Registra uma transação para sobrescrever um objeto com outro objeto.
 a| 
S3 clientes

Clientes Swift
 a| 
xref:ovwr-object-overwrite.adoc[OVWR: Substituição de objetos]



 a| 
SDEL
 a| 
S3 DELETE: Registra uma transação bem-sucedida para excluir um objeto ou um bucket.

*Nota:* se a transação operar em um subrecurso, a mensagem de auditoria incluirá o campo S3SR.
 a| 
Cliente S3
 a| 
xref:sdel-s3-delete.adoc[SDEL: S3 DELETE]



 a| 
SPOS
 a| 
S3 POST: Registra uma transação bem-sucedida para restaurar um objeto do armazenamento do AWS Glacier para um pool de armazenamento em nuvem.
 a| 
Cliente S3
 a| 
xref:spos-s3-post.adoc[SPOS: S3 POST]



 a| 
SPUT
 a| 
S3 put: Registra uma transação bem-sucedida para criar um novo objeto ou bucket.

*Nota:* se a transação operar em um subrecurso, a mensagem de auditoria incluirá o campo S3SR.
 a| 
Cliente S3
 a| 
xref:sput-s3-put.adoc[SPUT: S3 PUT]



 a| 
SUPD
 a| 
S3 metadados atualizados: Registra uma transação bem-sucedida para atualizar os metadados de um objeto ou bucket existente.
 a| 
Cliente S3
 a| 
xref:supd-s3-metadata-updated.adoc[SUPD: S3 metadados atualizados]



 a| 
WDEL
 a| 
Swift DELETE: Registra uma transação bem-sucedida para excluir um objeto ou contentor.
 a| 
Cliente Swift
 a| 
xref:wdel-swift-delete.adoc[WDEL: Swift DELETE]



 a| 
WPUT
 a| 
Swift PUT: Registra uma transação bem-sucedida para criar um novo objeto ou contentor.
 a| 
Cliente Swift
 a| 
xref:wput-swift-put.adoc[WPUT: Swift PUT]

|===