---
permalink: audit/object-delete-transactions.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, transaction, transactions, Object delete, S3 delete, Swift delete, S3, Swift, SDEL, WDEL 
summary: 'Você pode identificar transações de exclusão de objetos no log de auditoria localizando mensagens de auditoria específicas da API (S3 e Swift).' 
---
= Eliminar transações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode identificar transações de exclusão de objetos no log de auditoria localizando mensagens de auditoria específicas da API (S3 e Swift).

Nem todas as mensagens de auditoria geradas durante uma transação de exclusão são listadas nas tabelas a seguir. Apenas as mensagens necessárias para rastrear a transação de exclusão são incluídas.



== S3 exclua mensagens de auditoria

|===
| Código | Nome | Descrição | Traçado | Consulte 


 a| 
SDEL
 a| 
S3 Eliminar
 a| 
Solicitação feita para excluir o objeto de um intervalo.
 a| 
CBID, S3KY
 a| 
xref:sdel-s3-delete.adoc[SDEL: S3 DELETE]

|===


== Swift delete mensagens de auditoria

|===
| Código | Nome | Descrição | Traçado | Consulte 


 a| 
WDEL
 a| 
Eliminação rápida
 a| 
Solicitação feita para excluir o objeto de um recipiente ou do recipiente.
 a| 
CBID, WOBJ
 a| 
xref:wdel-swift-delete.adoc[WDEL: Swift DELETE]

|===