---
permalink: audit/object-storage-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, object storage, object management, object retrieval, node transfer, verification, APCT, ARCB, ARCE, ARCT, AREM, ASCE, ASCT, ATCE, AVCC, CBSE, CBRE, SCMT, SREM 
summary: Você deve estar familiarizado com as mensagens de auditoria pertencentes à categoria de auditoria de armazenamento de objetos. Estes são eventos relacionados ao armazenamento e gerenciamento de objetos no sistema StorageGRID. Isso inclui armazenamento de objetos e recuperações, transferências de nó de grade para nó de grade e verificações. 
---
= Mensagens de auditoria de armazenamento de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar familiarizado com as mensagens de auditoria pertencentes à categoria de auditoria de armazenamento de objetos. Estes são eventos relacionados ao armazenamento e gerenciamento de objetos no sistema StorageGRID. Isso inclui armazenamento de objetos e recuperações, transferências de nó de grade para nó de grade e verificações.

|===
| Código | Descrição | Consulte 


 a| 
APCT
 a| 
Limpeza de arquivamento da camada da nuvem: Os dados de objetos arquivados são excluídos de um sistema de storage de arquivamento externo, que se conecta ao StorageGRID por meio da API S3.
 a| 
xref:apct-archive-purge-from-cloud-tier.adoc[APCT: Purga de arquivamento do nível de nuvem]



 a| 
ARCB
 a| 
Início da recuperação de objetos de arquivamento: O serviço ARC inicia a recuperação de dados de objetos do sistema de armazenamento de arquivos externo.
 a| 
xref:arcb-archive-object-retrieve-begin.adoc[ARCB: Início da recuperação de objetos de arquivamento]



 a| 
ARCE
 a| 
Fim de recuperação de objetos de arquivamento: Os dados de objetos foram recuperados de um sistema de armazenamento de arquivos externo e o serviço ARC relata o status da operação de recuperação.
 a| 
xref:arce-archive-object-retrieve-end.adoc[ARCE: Fim de recuperação de objetos de arquivamento]



 a| 
ARCT
 a| 
Recuperação de arquivos do Cloud-Tier: Os dados de objetos arquivados são recuperados de um sistema de armazenamento de arquivamento externo, que se coneta ao StorageGRID por meio da API S3.
 a| 
xref:arct-archive-retrieve-from-cloud-tier.adoc[ARCT: Recuperação de arquivos do Cloud-Tier]



 a| 
ACEM
 a| 
Remoção de objeto de arquivamento: Um bloco de conteúdo foi excluído com sucesso ou sem sucesso do sistema de armazenamento de arquivos externo.
 a| 
xref:arem-archive-object-remove.adoc[AFEM: Remoção de objetos de Arquivo]



 a| 
ASCE
 a| 
Fim do armazenamento de objetos de arquivamento: Um bloco de conteúdo foi gravado no sistema de armazenamento de arquivos externo e o serviço ARC relata o status da operação de gravação.
 a| 
xref:asce-archive-object-store-end.adoc[ASCE: Fim do armazenamento de objetos de Arquivo]



 a| 
ASCT
 a| 
Camada de nuvem: Os dados de objetos são armazenados em um sistema de storage de arquivamento externo, que se conecta ao StorageGRID por meio da API S3.
 a| 
xref:asct-archive-store-cloud-tier.adoc[ASCT: Archive Store Cloud-Tier]



 a| 
ATCE
 a| 
Início do armazenamento de objetos de arquivamento: A gravação de um bloco de conteúdo em um armazenamento de arquivamento externo foi iniciada.
 a| 
xref:atce-archive-object-store-begin.adoc[ATCE: Início do armazenamento de objetos de arquivo]



 a| 
AVCC
 a| 
Archive Validate Cloud-Tier Configuration: As configurações de conta e bucket fornecidas foram validadas com êxito ou sem sucesso.
 a| 
xref:avcc-archive-validate-cloud-tier-configuration.adoc[AVCC: Arquivamento Validar Configuração de nível de nuvem]



 a| 
CBSE
 a| 
Fim de envio de objeto: A entidade de origem concluiu uma operação de transferência de dados de nó de grade para nó de grade.
 a| 
xref:cbse-object-send-end.adoc[CBSE: Fim de envio de objeto]



 a| 
CBRE
 a| 
Fim de recebimento de objeto: A entidade de destino concluiu uma operação de transferência de dados de nó de grade para nó de grade.
 a| 
xref:cbre-object-receive-end.adoc[CBRE: Fim de recebimento do objeto]



 a| 
SCMT
 a| 
Object Store commit: Um bloco de conteúdo foi completamente armazenado e verificado, e agora pode ser solicitado.
 a| 
xref:scmt-object-store-commit.adoc[SCMT: Confirmação de armazenamento de objetos]



 a| 
SREM
 a| 
Remoção do armazenamento de objetos: Um bloco de conteúdo foi excluído de um nó de grade e não pode mais ser solicitado diretamente.
 a| 
xref:srem-object-store-remove.adoc[SREM: Armazenamento de objetos Remover]

|===