---
permalink: audit/svru-object-store-verify-unknown.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRU, Object Store Verify Unknown 
summary: O componente de armazenamento do serviço LDR verifica continuamente todas as cópias de dados de objetos replicados no armazenamento de objetos. Esta mensagem é emitida quando uma cópia desconhecida ou inesperada de dados de objetos replicados é detetada no armazenamento de objetos e movida para o diretório de quarentena. 
---
= SVRU: Verificação do armazenamento de objetos desconhecido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O componente de armazenamento do serviço LDR verifica continuamente todas as cópias de dados de objetos replicados no armazenamento de objetos. Esta mensagem é emitida quando uma cópia desconhecida ou inesperada de dados de objetos replicados é detetada no armazenamento de objetos e movida para o diretório de quarentena.

|===
| Código | Campo | Descrição 


 a| 
FPTH
 a| 
Caminho do ficheiro
 a| 
O caminho do arquivo da cópia de objeto inesperada.



 a| 
RSLT
 a| 
Resultado
 a| 
Este campo tem o valor 'NONE'. RSLT é um campo de mensagem obrigatório, mas não é relevante para esta mensagem. 'NENHUM' é usado em vez de 'SUCS' para que esta mensagem não seja filtrada.

|===
*Nota:* a mensagem de auditoria SVRU: Object Store Verify Unknown deve ser monitorada de perto. Isso significa que cópias inesperadas de dados de objetos foram detetadas no armazenamento de objetos. Essa situação deve ser investigada imediatamente para determinar como essas cópias foram criadas, pois pode indicar tentativas de adulteração de conteúdo ou falhas iminentes de hardware.
