---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Você deve entender como seu sistema StorageGRID será afetado durante a atualização. 
---
= Como seu sistema é afetado durante a atualização
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve entender como seu sistema StorageGRID será afetado durante a atualização.



== As atualizações do StorageGRID não causam interrupções

O sistema StorageGRID pode obter e recuperar dados de aplicativos clientes durante todo o processo de atualização. Os nós de grade são derrubados um de cada vez durante a atualização, portanto, não há um momento em que todos os nós de grade estão indisponíveis.

Para permitir disponibilidade contínua, você deve garantir que os objetos sejam armazenados de forma redundante usando as políticas de ILM apropriadas. Você também deve garantir que todos os clientes externos S3 ou Swift estejam configurados para enviar solicitações para um dos seguintes:

* Um endpoint StorageGRID configurado como um grupo de alta disponibilidade (HA)
* Um balanceador de carga de terceiros de alta disponibilidade
* Vários nós de gateway para cada cliente
* Vários nós de storage para cada cliente




== O firmware do dispositivo foi atualizado

Durante a atualização do StorageGRID 11,6:

* Todos os nós do dispositivo StorageGRID são atualizados automaticamente para a versão 3,6 do firmware do instalador do StorageGRID Appliance.
* Os dispositivos SG6060 e SGF6024 são atualizados automaticamente para a versão 3B07.EX do firmware do BIOS e para a versão do firmware do BMC BMC 3.93.07.
* Os dispositivos SG100 e SG1000 são atualizados automaticamente para a versão 3B12.EC do firmware do BIOS e para a versão 4.67.07 do firmware do BMC.




== Os alertas podem ser acionados

Os alertas podem ser acionados quando os serviços começam e param e quando o sistema StorageGRID está operando como um ambiente de versão mista (alguns nós de grade executando uma versão anterior, enquanto outros foram atualizados para uma versão posterior). Outros alertas podem ser acionados após a conclusão da atualização.

Por exemplo, você pode ver o alerta *não é possível se comunicar com o nó* quando os serviços são interrompidos, ou você pode ver o alerta *erro de comunicação do Cassandra* quando alguns nós foram atualizados para o StorageGRID 11,6, mas outros nós ainda estão executando o StorageGRID 11,5. Em geral, esses alertas serão apagados quando a atualização for concluída.

O alerta *ILM Placement unachievable* pode ser acionado quando os nós de armazenamento são interrompidos durante a atualização para o StorageGRID 11,6. Esse alerta pode persistir por 1 dia após a conclusão da atualização.

Se você usar valores personalizados para as marcas d'água do volume de armazenamento, o alerta *baixa substituição da marca d'água somente leitura* poderá ser acionado após a conclusão da atualização. xref:../monitor/troubleshoot-low-watermark-alert.adoc[Solucionar problemas de alertas de substituição de marca d'água somente leitura baixa]Consulte para obter detalhes.

Após a conclusão da atualização, você pode revisar qualquer alerta relacionado a atualização selecionando *alertas resolvidos recentemente* ou *alertas atuais* no Painel do Gerenciador de Grade.



== Muitas notificações SNMP são geradas

Esteja ciente de que um grande número de notificações SNMP pode ser gerado quando os nós de grade são interrompidos e reiniciados durante a atualização. Para evitar notificações excessivas, desmarque a caixa de seleção *Ativar notificações de agente SNMP* (*CONFIGURAÇÃO* *Monitoramento* *agente SNMP*) para desativar as notificações SNMP antes de iniciar a atualização. Em seguida, reative as notificações após a atualização estar concluída.



== As alterações de configuração são restritas


NOTE: A lista de alterações de configuração restritas pode mudar de release para release. Ao atualizar para outra versão do StorageGRID, consulte a lista nas instruções de atualização apropriadas.

Até que a tarefa *Ativar novo recurso* seja concluída:

* Não faça alterações na configuração da grade.
* Não altere a configuração do nível de auditoria nem configure um servidor syslog externo.
* Não ative ou desative nenhum novo recurso.
* Não atualize a configuração do ILM. Caso contrário, você pode experimentar comportamento inconsistente e inesperado de ILM.
* Não aplique um hotfix ou recupere um nó de grade.
* Não é possível gerenciar grupos de HA, interfaces VLAN ou pontos de extremidade do balanceador de carga durante a atualização para o StorageGRID 11,6.


Até que a tarefa *etapas de atualização final* seja concluída:

* Não execute um procedimento de expansão.
* Não efetue um procedimento de desativação.




== Não é possível visualizar os detalhes do bucket ou gerenciar buckets do Gerenciador do locatário

Durante a atualização para o StorageGRID 11,6 (ou seja, enquanto o sistema estiver operando como um ambiente de versão mista), não é possível exibir detalhes do bucket ou gerenciar buckets usando o Gerenciador do locatário. Um dos seguintes erros aparece na página baldes no Tenant Manager:

* "Você não pode usar esta API enquanto estiver atualizando para 11,6."
* "'você não pode ver detalhes de controle de versão do bucket no Tenant Manager enquanto estiver atualizando para o 11,6.'"


Este erro será resolvido após a atualização para o 11,6 estar concluída.

.Solução alternativa
Enquanto a atualização do 11,6 estiver em andamento, use as seguintes ferramentas para exibir detalhes do bucket ou gerenciar buckets, em vez de usar o Gerenciador do locatário:

* Para executar operações S3 padrão em um bucket, use a API REST do S3 ou a API de gerenciamento do locatário.
* Para executar operações personalizadas do StorageGRID em um bucket (por exemplo, exibindo e modificando o nível de consistência do bucket, habilitando ou desativando as atualizações do último tempo de acesso ou configurando a integração de pesquisa), use a API de Gerenciamento do locatário.


xref:../tenant/understanding-tenant-management-api.adoc[Entenda a API de gerenciamento do locatário]Consulte e xref:../s3/index.adoc[Use S3] para obter instruções.
