---
permalink: sg100-1000/configuring-snmp-settings-for-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, SNMP, configure, setup, set up 
summary: Se estiver familiarizado com a configuração do SNMP para hardware, pode utilizar a interface BMC para configurar as definições SNMP para o utilitário de serviços. Você pode fornecer strings de comunidade seguras, ativar Trap SNMP e especificar até cinco destinos SNMP. 
---
= Configure as definições SNMP para o utilitário de serviços
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se estiver familiarizado com a configuração do SNMP para hardware, pode utilizar a interface BMC para configurar as definições SNMP para o utilitário de serviços. Você pode fornecer strings de comunidade seguras, ativar Trap SNMP e especificar até cinco destinos SNMP.

.O que você vai precisar
* Você sabe como acessar o painel do BMC.
* Tem experiência em configurar definições SNMP para equipamento SNMPv1-v2c.



NOTE: As definições do BMC efetuadas por este procedimento poderão não ser preservadas se o aparelho falhar e tiver de ser substituído. Certifique-se de que tem um registo de todas as definições aplicadas, para que possam ser facilmente reaplicadas após uma substituição de hardware, se necessário.

.Passos
. No painel BMC, selecione *Configurações* *Configurações* *Configurações SNMP*.
. Na página Configurações SNMP, selecione *Ativar SNMP V1/V2* e, em seguida, forneça uma String comunitária somente leitura e uma String Comunidade de leitura-escrita.
+
A String da Comunidade somente leitura é como uma ID de usuário ou senha. Você deve alterar esse valor para evitar que intrusos obtenham informações sobre a configuração da rede. A cadeia de Comunidade de leitura-escrita protege o dispositivo contra alterações não autorizadas.

. Opcionalmente, selecione *Ativar Trap* e insira as informações necessárias.
+

IMPORTANT: Introduza o IP de destino para cada trap SNMP utilizando um endereço IP. Nomes de domínio totalmente qualificados não são suportados.

+
Ative traps se quiser que o utilitário de serviços envie notificações imediatas para um console SNMP quando ele estiver em um estado incomum. Os traps podem indicar condições de ligação para cima/para baixo, temperaturas que excedem determinados limites ou tráfego elevado.

. Opcionalmente, clique em *Send Test Trap* para testar suas configurações.
. Se as configurações estiverem corretas, clique em *Salvar*.

