---
permalink: sg100-1000/overview-of-installation-rest-apis.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, installation REST API, REST API, installation REST APIs, REST APIs, Appliance Installer API, Appliance Installer APIs, Install API, Install APIs, Installer API, Installer APIs, Installation API, Installation APIs, api, apis 
summary: 'O StorageGRID fornece duas APIs REST para executar tarefas de instalação: A API de instalação do StorageGRID e a API do instalador do dispositivo StorageGRID.' 
---
= Visão geral das APIs REST de instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece duas APIs REST para executar tarefas de instalação: A API de instalação do StorageGRID e a API do instalador do dispositivo StorageGRID.

Ambas as APIs usam a plataforma de API de código aberto Swagger para fornecer a documentação da API. O Swagger permite que desenvolvedores e não desenvolvedores interajam com a API em uma interface de usuário que ilustra como a API responde a parâmetros e opções. Esta documentação pressupõe que você esteja familiarizado com as tecnologias da Web padrão e o formato de dados JSON (JavaScript Object Notation).


IMPORTANT: Todas as operações de API que você executa usando a página da Web do API Docs são operações ativas. Tenha cuidado para não criar, atualizar ou excluir dados de configuração ou outros dados por engano.

Cada comando REST API inclui o URL da API, uma ação HTTP, quaisquer parâmetros de URL necessários ou opcionais e uma resposta de API esperada.



== API de instalação do StorageGRID

A API de instalação do StorageGRID só está disponível quando você estiver configurando inicialmente seu sistema StorageGRID e, caso precise executar uma recuperação do nó de administração principal. A API de instalação pode ser acessada por HTTPS a partir do Gerenciador de Grade.

Para acessar a documentação da API, vá para a página da Web de instalação no nó de administração principal e selecione *Ajuda* *Documentação da API* na barra de menus.

A API de instalação do StorageGRID inclui as seguintes seções:

* *Config* -- operações relacionadas à versão do produto e versões da API. Você pode listar a versão de lançamento do produto e as principais versões da API suportadas por essa versão.
* *Grid* -- operações de configuração em nível de grade. Você pode obter e atualizar configurações de grade, incluindo detalhes de grade, sub-redes de rede de grade, senhas de grade e endereços IP de servidor NTP e DNS.
* *NODES* -- operações de configuração em nível de nó. Você pode recuperar uma lista de nós de grade, excluir um nó de grade, configurar um nó de grade, exibir um nó de grade e redefinir a configuração de um nó de grade.
* *Provisão* -- operações de provisionamento. Você pode iniciar a operação de provisionamento e exibir o status da operação de provisionamento.
* *Recovery* -- operações de recuperação do nó de administração principal. Você pode redefinir informações, carregar o pacote de recuperação, iniciar a recuperação e exibir o status da operação de recuperação.
* *Recovery-package* -- operações para baixar o Recovery Package.
* *Sites* -- operações de configuração no nível do local. Você pode criar, exibir, excluir e modificar um site.




== API do instalador do dispositivo StorageGRID

A API do instalador do dispositivo StorageGRID pode ser acessada por HTTPS a partir  `_Controller_IP_:8443`do .

Para acessar a documentação da API, vá para o Instalador do StorageGRID Appliance no appliance e selecione *Ajuda* *Documentação da API* na barra de menus.

A API do instalador do StorageGRID Appliance inclui as seguintes seções:

* *Clone* -- operações para configurar e controlar a clonagem de nós.
* *Encryption* -- operações para gerenciar a criptografia e visualizar o status da criptografia.
* *Configuração de hardware* -- operações para configurar as configurações do sistema no hardware conetado.
* *Installation* -- operações para iniciar a instalação do aparelho e para monitorar o status da instalação.
* *Networking* -- operações relacionadas à configuração de rede, administrador e rede cliente para um dispositivo StorageGRID e configurações de porta de dispositivo.
* *Setup* -- operações para ajudar na configuração inicial da instalação do dispositivo, incluindo solicitações para obter informações sobre o sistema e atualizar o IP do nó de administração principal.
* *SUPPORT* -- operações para reiniciar o controlador e obter logs.
* *Upgrade* -- operações relacionadas à atualização do firmware do appliance.
* * Uploadsg* -- operações para upload de arquivos de instalação do StorageGRID.

