---
permalink: sg100-1000/shut-down-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: Desligue o dispositivo de serviços para executar a manutenção de hardware. 
---
= Desligue o aparelho de serviços
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desligue o dispositivo de serviços para executar a manutenção de hardware.

.O que você vai precisar
* Você localizou fisicamente o dispositivo de serviços que requer manutenção no data center.
+
xref:locating-controller-in-data-center.adoc[Localizar o controlador em um data center]

* O aparelho foi xref:placing-appliance-into-maintenance-mode.adoc[colocado no modo de manutenção].


.Sobre esta tarefa
Para evitar interrupções de serviço, desligue o equipamento de serviços durante uma janela de manutenção programada, quando os períodos de interrupção de serviço são normalmente esperados.

.Passos
. Quando o aparelho tiver sido colocado no modo de manutenção, desligue o aparelho:
+

CAUTION: Tem de efetuar um corte de funcionamento controlado do aparelho introduzindo os comandos especificados abaixo. Desligar o aparelho utilizando o interrutor de alimentação resultará na perda de dados.

+
.. Faça login no nó de grade usando PuTTY ou outro cliente ssh:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



.. Desligue o aparelho de serviços
`*shutdown -h now*`
+
Esse comando pode levar até 10 minutos para ser concluído.



. Utilize um dos seguintes métodos para verificar se o aparelho está desligado:
+
** Olhe para o LED de alimentação na parte frontal do aparelho e confirme que está desligado.
** Verifique a página Power Control (controlo de alimentação) da interface do BMC para confirmar que o aparelho está desligado.



