---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Você deve instalar Ubuntu ou Debian em todos os hosts de grade. Use a ferramenta Matriz de interoperabilidade do NetApp para obter uma lista de versões suportadas. 
---
= Instale o Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o Linux em todos os hosts de grade. Utilize o https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para obter uma lista de versões suportadas.

.Passos
. Instale o Linux em todos os hosts de grade física ou virtual de acordo com as instruções do distribuidor ou seu procedimento padrão.
+

NOTE: Não instale nenhum ambiente de desktop gráfico. Ao instalar o Ubuntu, você deve selecionar *utilitários de sistema padrão*. Selecionar *OpenSSH Server* é recomendado para habilitar o acesso ssh aos seus hosts Ubuntu. Todas as outras opções podem permanecer não selecionadas.

. Certifique-se de que todos os hosts tenham acesso aos repositórios de pacotes Ubuntu ou Debian.
. Se a troca estiver ativada:
+
.. Execute o seguinte comando: `$ sudo swapoff --all`
.. Remova todas as entradas de troca de `/etc/fstab` para persistir as configurações.


+

IMPORTANT: A falha ao desativar completamente a troca pode reduzir drasticamente o desempenho.


