---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: Você deve manter seu sistema StorageGRID e serviços relacionados atualizados para se defender contra ataques. 
---
= Diretrizes de fortalecimento para atualizações de software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve manter seu sistema StorageGRID e serviços relacionados atualizados para se defender contra ataques.



== Atualizações para o software StorageGRID

Sempre que possível, você deve atualizar o software StorageGRID para a versão principal mais recente ou para a versão principal anterior. Manter o StorageGRID atualizado ajuda a reduzir o tempo em que as vulnerabilidades conhecidas estão ativas e reduz a área geral da superfície de ataque. Além disso, as versões mais recentes do StorageGRID geralmente contêm recursos de proteção de segurança que não estão incluídos em versões anteriores.

Quando um hotfix é necessário, o NetApp prioriza a criação de atualizações para as versões mais recentes. Alguns patches podem não ser compatíveis com versões anteriores.

Para baixar as versões e hotfixes mais recentes do StorageGRID, acesse a página de download do software StorageGRID. Para obter instruções passo a passo para atualizar o software StorageGRID, consulte as instruções para atualizar o StorageGRID. Para obter instruções sobre como aplicar um hotfix, consulte as instruções de recuperação e manutenção.



== Upgrades para serviços externos

Os serviços externos podem ter vulnerabilidades que afetam o StorageGRID indiretamente. Você deve garantir que os serviços dos quais o StorageGRID depende são atualizados. Esses serviços incluem LDAP, KMS (ou servidor KMIP), DNS e NTP.

Use a ferramenta Matriz de interoperabilidade do NetApp para obter uma lista de versões suportadas.



== Atualizações para hypervisors

Se seus nós do StorageGRID estiverem em execução no VMware ou em outro hypervisor, você deverá garantir que o software e o firmware do hypervisor estejam atualizados.

Use a ferramenta Matriz de interoperabilidade do NetApp para obter uma lista de versões suportadas.



== *Upgrade para nós Linux*

Se seus nós do StorageGRID estiverem usando plataformas host Linux, você deve garantir que as atualizações de segurança e as atualizações do kernel sejam aplicadas ao sistema operacional do host. Além disso, você deve aplicar atualizações de firmware a hardware vulnerável quando essas atualizações estiverem disponíveis.

Use a ferramenta Matriz de interoperabilidade do NetApp para obter uma lista de versões suportadas.

.Informações relacionadas
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^]

xref:../upgrade/index.adoc[Atualizar o software]

xref:../maintain/index.adoc[Recuperar e manter]

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]
