---
permalink: harden/other-hardening-guidelines.html 
sidebar: sidebar 
keywords: Hardening guidelines, security 
summary: Além de seguir as diretrizes de proteção para redes e nós StorageGRID, você deve seguir as diretrizes de proteção para outras áreas do sistema StorageGRID. 
---
= Outras diretrizes de endurecimento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Além de seguir as diretrizes de proteção para redes e nós StorageGRID, você deve seguir as diretrizes de proteção para outras áreas do sistema StorageGRID.



== Logs e mensagens de auditoria

Proteja sempre os logs do StorageGRID e a saída de mensagens de auditoria de forma segura. Os logs do StorageGRID e as mensagens de auditoria fornecem informações inestimáveis do ponto de vista de suporte e disponibilidade do sistema. Além disso, as informações e detalhes contidos nos logs do StorageGRID e na saída de mensagens de auditoria são geralmente de natureza sensível.

Configure o StorageGRID para enviar eventos de segurança para um servidor syslog externo. Se estiver usando a exportação syslog, selecione TLS e RELP/TLS para os protocolos de transporte.

Consulte as instruções para monitoramento e solução de problemas para obter mais informações sobre logs do StorageGRID. Consulte as instruções para mensagens de auditoria para obter mais informações sobre mensagens de auditoria do StorageGRID.



== NetApp AutoSupport

O recurso AutoSupport do StorageGRID permite que você monitore proativamente a integridade do sistema e envie mensagens e detalhes automaticamente para o suporte técnico da NetApp, para a equipe de suporte interna da organização ou para um parceiro de suporte. Por padrão, as mensagens AutoSupport para o suporte técnico do NetApp são ativadas quando o StorageGRID é configurado pela primeira vez.

O recurso AutoSupport pode ser desativado. No entanto, o NetApp recomenda habilitá-lo, pois o AutoSupport ajuda a acelerar a identificação e resolução de problemas caso surja algum problema no seu sistema StorageGRID.

O AutoSupport suporta HTTPS, HTTP e SMTP para protocolos de transporte. Devido à natureza sensível das mensagens AutoSupport, a NetApp recomenda fortemente o uso de HTTPS como o protocolo de transporte padrão para enviar mensagens AutoSupport para o suporte ao NetApp.

Opcionalmente, você pode configurar um proxy de administrador para obter mais controle sobre a comunicação do AutoSupport de nós de administração para o suporte técnico do NetApp. Consulte as etapas para criar um proxy de administrador nas instruções de administração do StorageGRID.



== Compartilhamento de recursos entre origens (CORS)

Você pode configurar o Compartilhamento de recursos entre origens (CORS) para um bucket do S3 se quiser que esse bucket e objetos nesse bucket estejam acessíveis a aplicativos da Web em outros domínios. Em geral, não ative o CORS a menos que seja necessário. Se CORS for necessário, restrinja-o a origens confiáveis.

Consulte as etapas para configurar o Compartilhamento de recursos entre origens (CORS) nas instruções para usar contas de locatário.



== Dispositivos de segurança externos

Uma solução completa de endurecimento deve abordar mecanismos de segurança fora do StorageGRID. O uso de dispositivos de infraestrutura adicionais para filtrar e limitar o acesso ao StorageGRID é uma maneira eficaz de estabelecer e manter uma postura de segurança rigorosa. Esses dispositivos de segurança externos incluem firewalls, sistemas de prevenção de intrusão (IPSs) e outros dispositivos de segurança.

Um balanceador de carga de terceiros é recomendado para tráfego de clientes não confiável. O balanceamento de carga de terceiros oferece mais controle e camadas adicionais de proteção contra ataques.

.Informações relacionadas
xref:../monitor/index.adoc[Monitorar e solucionar problemas]

xref:../audit/index.adoc[Rever registos de auditoria]

xref:../tenant/index.adoc[Use a conta de locatário]

xref:../admin/index.adoc[Administrar o StorageGRID]
