---
permalink: sg5600/verifying-receipt-of-autosupport.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, verify, verification, verifying, confirm, confirmation, confirming, autosupport, auto-support, status 
summary: Você deve verificar se o suporte técnico está recebendo suas mensagens do AutoSupport. Você pode encontrar o status do AutoSupport para seus sistemas no portal de consultores digitais. Verificar o recebimento dessas mensagens garante que o suporte técnico tenha suas informações se precisar de assistência. 
---
= Verifique a receção do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve verificar se o suporte técnico está recebendo suas mensagens do AutoSupport. Você pode encontrar o status do AutoSupport para seus sistemas no portal de consultores digitais. Verificar o recebimento dessas mensagens garante que o suporte técnico tenha suas informações se precisar de assistência.

.Sobre esta tarefa
O AutoSupport pode apresentar um dos seguintes Estados:

* *LIGADO*
+
Um STATUS LIGADO indica que o suporte técnico está recebendo mensagens AutoSupport do sistema.

* *OFF*
+
Um status OFF sugere que você pode ter desabilitado o AutoSupport porque o suporte técnico não recebeu um Registro semanal do sistema nos últimos 15 dias de calendário ou pode ter ocorrido uma alteração no ambiente ou na configuração (por exemplo).

* *DECLÍNIO*
+
Um status DE REJEIÇÃO significa que você notificou o suporte técnico de que não ativará o AutoSupport.



Depois que o suporte técnico recebe um Registro semanal do sistema, o status do AutoSupport muda para ATIVADO.

.Passos
. Vá para o site de suporte da NetApp em http://mysupport.netapp.com/["mysupport.NetApp.com"^] e entre no portal de consultores digitais.
. Se o estado do AutoSupport estiver DESLIGADO e acreditar que está incorreto, efetue o seguinte:
+
.. Verifique a configuração do sistema para garantir que você ativou o AutoSupport.
.. Verifique o ambiente e a configuração da rede para garantir que o sistema possa enviar mensagens para o suporte técnico.



