---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: 'Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) ou a API REST Swift para armazenar e recuperar objetos em um sistema StorageGRID.' 
---
= Use uma conta de locatário: Visão geral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma conta de locatário permite que você use a API REST do Simple Storage Service (S3) ou a API REST Swift para armazenar e recuperar objetos em um sistema StorageGRID.



== O que é uma conta de locatário?

Cada conta de locatário tem seus próprios grupos federados ou locais, usuários, buckets do S3 ou contentores Swift e objetos.

Opcionalmente, as contas de inquilino podem ser usadas para segregar objetos armazenados por diferentes entidades. Por exemplo, várias contas de inquilino podem ser usadas para qualquer um desses casos de uso:

* *Caso de uso corporativo:* se o sistema StorageGRID estiver sendo usado dentro de uma empresa, o armazenamento de objetos da grade pode ser segregado pelos diferentes departamentos da organização. Por exemplo, pode haver contas de inquilino para o departamento de marketing, o departamento de suporte ao cliente, o departamento de recursos humanos e assim por diante.
+

NOTE: Se você usar o protocolo cliente S3, também poderá usar buckets e políticas de bucket do S3 para segregar objetos entre os departamentos de uma empresa. Você não precisa criar contas de locatário separadas. Consulte xref:../s3/index.adoc[Instruções para a implementação de aplicativos cliente S3].

* * Caso de uso do provedor de serviços:* se o sistema StorageGRID estiver sendo usado por um provedor de serviços, o armazenamento de objetos da grade pode ser segregado pelas diferentes entidades que alugam o armazenamento. Por exemplo, pode haver contas de inquilino para a empresa A, empresa B, empresa C e assim por diante.




== Como criar uma conta de locatário

As contas de inquilino são criadas por um xref:../admin/managing-tenants.adoc[Administrador de grade do StorageGRID usando o Gerenciador de grade]. Ao criar uma conta de locatário, o administrador da grade especifica as seguintes informações:

* Nome de exibição para o locatário (o ID da conta do locatário é atribuído automaticamente e não pode ser alterado).
* Se a conta de locatário usará o S3 ou Swift.
* Para contas de inquilino S3: Se a conta de inquilino tem permissão para usar serviços de plataforma. Se o uso de serviços de plataforma for permitido, a grade deve ser configurada para suportar seu uso.
* Opcionalmente, uma cota de armazenamento para a conta de locatário - o número máximo de gigabytes, terabytes ou petabytes disponíveis para os objetos do locatário. A cota de armazenamento de um locatário representa uma quantidade lógica (tamanho do objeto), e não uma quantidade física (tamanho no disco).
* Se a federação de identidade estiver ativada para o sistema StorageGRID, qual grupo federado tem permissão de acesso root para configurar a conta de locatário.
* Se o logon único (SSO) não estiver em uso para o sistema StorageGRID, se a conta do locatário usará sua própria origem de identidade ou compartilhará a origem de identidade da grade e a senha inicial para o usuário raiz local do locatário.


Além disso, os administradores de grade podem ativar a configuração bloqueio de objeto S3 para o sistema StorageGRID se as contas de locatário S3 precisarem cumprir os requisitos regulamentares. Quando o bloqueio de objeto S3 está ativado, todas as contas de locatário do S3 podem criar e gerenciar buckets compatíveis.



=== Configurar locatários do S3

Depois de um xref:../admin/creating-tenant-account.adoc[S3 conta de locatário é criada], você pode acessar o Gerenciador do Locatário para executar tarefas como as seguintes:

* Configurando a federação de identidade (a menos que a origem de identidade seja compartilhada com a grade) ou criando grupos e usuários locais
* Gerenciando chaves de acesso S3
* Criação e gerenciamento de buckets do S3, incluindo buckets em conformidade
* Usando serviços de plataforma (se ativado)
* Monitoramento do uso do storage



IMPORTANT: Embora você possa criar e gerenciar buckets do S3 com o Gerenciador do locatário, você precisa ter xref:../s3/index.adoc[S3 teclas de acesso e usar a API REST do S3 para ingerir e gerenciar objetos]o .



=== Configurar os locatários Swift

Depois de um xref:../admin/creating-tenant-account.adoc[Conta de locatário Swift foi criada], você pode acessar o Gerenciador do Locatário para executar tarefas como as seguintes:

* Configurando a federação de identidade (a menos que a origem de identidade seja compartilhada com a grade) e criando grupos e usuários locais
* Monitoramento do uso do storage



IMPORTANT: Os usuários Swift devem ter a permissão de acesso root para acessar o Gerenciador do locatário. No entanto, a permissão de acesso root não permite que os usuários se autentiquem no xref:../swift/index.adoc[Swift REST API] para criar containers e ingerir objetos. Os usuários devem ter a permissão Swift Administrator para se autenticar na API Swift REST.



== Use o Gerenciador do Locatário

O Gerenciador do Locatário permite gerenciar todos os aspetos de uma conta de locatário do StorageGRID.

Você pode usar o Gerenciador do locatário para monitorar o uso do armazenamento de uma conta de locatário e gerenciar usuários com federação de identidade ou criando grupos e usuários locais. Para contas de locatários do S3, você também pode gerenciar chaves do S3, gerenciar buckets do S3 e configurar serviços de plataforma.
