---
permalink: rhel/required-materials.html 
sidebar: sidebar 
keywords: installation materials red hat linux 
summary: Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários. 
---
= Materiais necessários
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários.

[cols="1a,2a"]
|===
| Item | Notas 


 a| 
Licença NetApp StorageGRID
 a| 
Você deve ter uma licença NetApp válida e assinada digitalmente.

*Nota*: Uma licença de não produção, que pode ser usada para testes e grades de prova de conceito, está incluída no arquivo de instalação do StorageGRID.



 a| 
Arquivo de instalação do StorageGRID
 a| 
Você deve xref:downloading-and-extracting-storagegrid-installation-files.adoc[Baixe o arquivo de instalação do StorageGRID e extraia os arquivos].



 a| 
Serviço de laptop
 a| 
O sistema StorageGRID é instalado através de um computador portátil de serviço.

O computador portátil de serviço deve ter:

* Porta de rede
* Cliente SSH (por exemplo, PuTTY)
* xref:../admin/web-browser-requirements.adoc[Navegador da Web suportado]




 a| 
Documentação do StorageGRID
 a| 
* xref:../release-notes/index.adoc[Notas de lançamento]
* xref:../admin/index.adoc[Instruções para administrar o StorageGRID]


|===
.Informações relacionadas
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]
