---
permalink: admin/configuring-audit-clients-for-workgroup.html 
sidebar: sidebar 
keywords: audit client for workgroup 
summary: Execute este procedimento para cada nó de administrador em uma implantação do StorageGRID a partir da qual você deseja recuperar mensagens de auditoria. 
---
= Configurar clientes de auditoria para o Workgroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Execute este procedimento para cada nó de administrador em uma implantação do StorageGRID a partir da qual você deseja recuperar mensagens de auditoria.

.O que você vai precisar
* Tem o `Passwords.txt` ficheiro com a palavra-passe da conta root/admin (disponível no REFERIDO pacote).
* Você tem o `Configuration.txt` arquivo (disponível no REFERIDO pacote).


.Sobre esta tarefa
A exportação de auditoria por meio do CIFS/Samba foi obsoleta e será removida em uma futura versão do StorageGRID.

.Passos
. Faça login no nó de administração principal:
+
.. Introduza o seguinte comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Confirme se todos os serviços têm estado em execução ou verificado: `storagegrid-status`
+
Se todos os serviços não estiverem em execução ou verificados, resolva os problemas antes de continuar.

. Volte para a linha de comando, pressione *Ctrl* * C*.
. Inicie o utilitário de configuração CIFS: `config_cifs.rb`
+
[listing]
----

---------------------------------------------------------------------
| Shares                 | Authentication         | Config          |
---------------------------------------------------------------------
| add-audit-share        | set-authentication     | validate-config |
| enable-disable-share   | set-netbios-name       | help            |
| add-user-to-share      | join-domain            | exit            |
| remove-user-from-share | add-password-server    |                 |
| modify-group           | remove-password-server |                 |
|                        | add-wins-server        |                 |
|                        | remove-wins-server     |                 |
---------------------------------------------------------------------
----
. Defina a autenticação para o grupo de trabalho do Windows:
+
Se a autenticação já tiver sido definida, é apresentada uma mensagem de aviso. Se a autenticação já tiver sido definida, vá para a próxima etapa.

+
.. Introduza: `set-authentication`
.. Quando solicitado para a instalação do Windows Workgroup ou do ative Directory, digite: `workgroup`
.. Quando solicitado, insira um nome do grupo de trabalho: `_workgroup_name_`
.. Quando solicitado, crie um nome NetBIOS significativo: `_netbios_name_`
+
ou

+
Pressione *Enter* para usar o nome do host do Admin Node como o nome NetBIOS.

+
O script reinicia o servidor Samba e as alterações são aplicadas. Isso deve levar menos de um minuto. Depois de definir a autenticação, adicione um cliente de auditoria.

.. Quando solicitado, pressione *Enter*.
+
O utilitário de configuração CIFS é exibido.



. Adicionar um cliente de auditoria:
+
.. Introduza: `add-audit-share`
+

NOTE: O compartilhamento é adicionado automaticamente como somente leitura.

.. Quando solicitado, adicione um usuário ou grupo: `_user_`
.. Quando solicitado, insira o nome de usuário da auditoria: `_audit_user_name_`
.. Quando solicitado, insira uma senha para o usuário de auditoria: `_password_`
.. Quando solicitado, digite novamente a mesma senha para confirmá-la: `_password_`
.. Quando solicitado, pressione *Enter*.
+
O utilitário de configuração CIFS é exibido.



+

NOTE: Não há necessidade de inserir um diretório. O nome do diretório de auditoria é predefinido.

. Se mais de um usuário ou grupo tiver permissão para acessar o compartilhamento de auditoria, adicione os usuários adicionais:
+
.. Introduza: `add-user-to-share`
+
É apresentada uma lista numerada de partilhas ativadas.

.. Quando solicitado, insira o número do compartilhamento de auditoria-exportação: `_share_number_`
.. Quando solicitado, adicione um usuário ou grupo: `user`
+
ou `group`

.. Quando solicitado, insira o nome do usuário ou grupo de auditoria: `_audit_user or audit_group_`
.. Quando solicitado, pressione *Enter*.
+
O utilitário de configuração CIFS é exibido.

.. Repita essas subetapas para cada usuário ou grupo adicional que tenha acesso ao compartilhamento de auditoria.


. Opcionalmente, verifique sua configuração: `validate-config`
+
Os serviços são verificados e exibidos. Você pode ignorar com segurança as seguintes mensagens:

+
[listing]
----
Can't find include file /etc/samba/includes/cifs-interfaces.inc
Can't find include file /etc/samba/includes/cifs-filesystem.inc
Can't find include file /etc/samba/includes/cifs-custom-config.inc
Can't find include file /etc/samba/includes/cifs-shares.inc
rlimit_max: increasing rlimit_max (1024) to minimum Windows limit (16384)
----
+
.. Quando solicitado, pressione *Enter*.
+
A configuração do cliente de auditoria é exibida.

.. Quando solicitado, pressione *Enter*.
+
O utilitário de configuração CIFS é exibido.



. Feche o utilitário de configuração CIFS: `exit`
. Inicie o serviço Samba: `service smbd start`
. Se a implantação do StorageGRID for um único local, vá para a próxima etapa.
+
ou

+
Opcionalmente, se a implantação do StorageGRID incluir nós de administração em outros sites, habilite esse compartilhamento de auditoria conforme necessário:

+
.. Faça login remotamente no Admin Node de um site:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


.. Repita as etapas para configurar o compartilhamento de auditoria para cada nó Admin adicional.
.. Feche o login remoto do shell seguro para o Admin Node remoto: `exit`


. Faça logout do shell de comando: `exit`

