---
permalink: admin/configuring-audit-client-access.html 
sidebar: sidebar 
keywords: audit client, ams, audit management service 
summary: 'O Admin Node, por meio do serviço do sistema de Gerenciamento de Auditoria (AMS), Registra todos os eventos do sistema auditados em um arquivo de log disponível por meio do compartilhamento de auditoria, que é adicionado a cada Admin Node na instalação. Para facilitar o acesso aos logs de auditoria, você pode configurar o acesso do cliente para compartilhamentos de auditoria para CIFS e NFS.' 
---
= Configurar acesso de cliente de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Admin Node, por meio do serviço do Audit Management System (AMS), Registra todos os eventos do sistema auditados em um arquivo de log disponível por meio do compartilhamento de auditoria, que é adicionado a cada Admin Node na instalação. Para facilitar o acesso aos logs de auditoria, você pode configurar o acesso do cliente para compartilhamentos de auditoria para CIFS e NFS.

O sistema StorageGRID usa reconhecimento positivo para evitar a perda de mensagens de auditoria antes de serem gravadas no arquivo de log. Uma mensagem permanece na fila em um serviço até que o serviço AMS ou um serviço de relé de auditoria intermediária tenha reconhecido o controle dele.

Para obter mais informações, xref:../audit/index.adoc[Rever registos de auditoria]consulte .


NOTE: A exportação de auditoria por meio do CIFS/Samba foi obsoleta e será removida em uma futura versão do StorageGRID. Se você tiver a opção de usar CIFS ou NFS, escolha NFS.
