---
permalink: admin/manage-s3-select-for-tenant-accounts.html 
sidebar: sidebar 
keywords: s3 select, selectobjectcontent, best practices 
summary: Você pode permitir que certos locatários do S3 usem o S3 Select para emitir solicitações SelectObjectContent em objetos individuais. 
---
= Gerenciar S3 Selecione para contas de inquilino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode permitir que certos locatários do S3 usem o S3 Select para emitir solicitações SelectObjectContent em objetos individuais.

S3 Select fornece uma maneira eficiente de pesquisar grandes quantidades de dados sem ter que implantar um banco de dados e recursos associados para habilitar pesquisas. Ele também reduz o custo e a latência da recuperação de dados.



== O que é o S3 Select?

S3 Select permite que os clientes S3 usem as solicitações SelectObjectContent para filtrar e recuperar apenas os dados necessários de um objeto. A implementação do StorageGRID do S3 Select inclui um subconjunto de comandos e recursos do S3 Select.



== Considerações e requisitos para usar o S3 Select

O StorageGRID requer o seguinte para consultas S3 Select:

* O objeto que você deseja consultar está em formato CSV ou é um arquivo compactado GZIP ou bzip2 contendo um arquivo formatado CSV.
* Aos locatários devem ser concedidos S3 Selecione a capacidade pelo administrador da grade. Selecione *permitir S3 Selecionar* quando xref:creating-tenant-account.adoc[criando um locatário] ou xref:editing-tenant-account.adoc[editando um locatário].
* A solicitação SelectObjectContent deve ser enviada para um xref:configuring-load-balancer-endpoints.adoc[Ponto de extremidade do balanceador de carga StorageGRID]. Os nós de administrador e gateway usados pelo endpoint devem ser SG100 ou SG1000 nós de dispositivo ou nós de software baseados em VMware.


Observe as seguintes limitações:

* Nós de balanceador de carga bare-metal não são compatíveis.
* As consultas não podem ser enviadas diretamente para nós de storage.
* As consultas enviadas através do serviço CLB obsoleto não são suportadas.



IMPORTANT: As solicitações SelectObjectContent podem diminuir o desempenho do balanceador de carga para todos os clientes S3 e todos os locatários. Ative esse recurso somente quando necessário e somente para locatários confiáveis.

Consulte xref:../s3/use-s3-select.adoc[Instruções para utilizar o S3 Select].

Para visualizar xref:../monitor/reviewing-support-metrics.adoc[Gráficos de Grafana] as operações S3 Select ao longo do tempo, selecione *SUPPORT* > *Tools* > *Metrics* no Grid Manager.
