---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: 'Os aplicativos clientes podem se conetar ao StorageGRID usando o endereço IP de um nó de grade e o número da porta de um serviço nesse nó. Se os grupos de alta disponibilidade (HA) estiverem configurados, os aplicativos cliente poderão se conetar usando o endereço IP virtual do grupo HA.' 
---
= Resumo: Endereços IP e portas para conexões de clientes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os aplicativos clientes podem se conetar ao StorageGRID usando o endereço IP de um nó de grade e o número da porta de um serviço nesse nó. Se os grupos de alta disponibilidade (HA) estiverem configurados, os aplicativos clientes poderão se conetar usando o endereço IP virtual do grupo HA.

.Sobre esta tarefa
Esta tabela resume as diferentes maneiras pelas quais os clientes podem se conetar ao StorageGRID e os endereços IP e as portas usadas para cada tipo de conexão. As instruções descrevem como localizar essas informações no Gerenciador de Grade se os pontos de extremidade do balanceador de carga e os grupos de alta disponibilidade (HA) já estiverem configurados.

[cols="1a,1a,1a,1a"]
|===
| Onde a conexão é feita | Serviço ao qual o cliente se coneta | Endereço IP | Porta 


 a| 
Grupo HA
 a| 
Balanceador de carga
 a| 
Endereço IP virtual de um grupo HA
 a| 
* Porta de extremidade do balanceador de carga




 a| 
Grupo HA
 a| 
CLB

*Nota:* o serviço CLB está obsoleto.
 a| 
Endereço IP virtual de um grupo HA
 a| 
Portas S3 padrão:

* HTTPS: 8082
* HTTP: 8084


Portas Swift padrão:

* HTTPS:8083
* HTTP:8085




 a| 
Nó de administração
 a| 
Balanceador de carga
 a| 
Endereço IP do nó Admin
 a| 
* Porta de extremidade do balanceador de carga




 a| 
Nó de gateway
 a| 
Balanceador de carga
 a| 
Endereço IP do nó de gateway
 a| 
* Porta de extremidade do balanceador de carga




 a| 
Nó de gateway
 a| 
CLB

*Nota:* o serviço CLB está obsoleto.
 a| 
Endereço IP do nó de gateway

*Nota:* por padrão, as portas HTTP para CLB e LDR não estão ativadas.
 a| 
Portas S3 padrão:

* HTTPS: 8082
* HTTP: 8084


Portas Swift padrão:

* HTTPS:8083
* HTTP:8085




 a| 
Nó de storage
 a| 
LDR
 a| 
Endereço IP do nó de armazenamento
 a| 
Portas S3 padrão:

* HTTPS: 18082
* HTTP: 18084


Portas Swift padrão:

* HTTPS: 18083
* HTTP:18085


|===
.Exemplos
Para conetar um cliente S3 ao ponto de extremidade do Load Balancer de um grupo de HA de nós de Gateway, use um URL estruturado como mostrado abaixo:

* `https://_VIP-of-HA-group:LB-endpoint-port_`


Por exemplo, se o endereço IP virtual do grupo HA for 192.0.2.5 e o número da porta de um endpoint do balanceador de carga S3 for 10443, um cliente S3 poderá usar o seguinte URL para se conetar ao StorageGRID:

* `\https://192.0.2.5:10443`


Para conetar um cliente Swift ao endpoint do Load Balancer de um grupo de HA de nós de Gateway, use um URL estruturado como mostrado abaixo:

* `https://_VIP-of-HA-group:LB-endpoint-port_`


Por exemplo, se o endereço IP virtual do grupo HA for 192.0.2.6 e o número da porta de um endpoint do Swift Load Balancer for 10444, um cliente Swift poderá usar o seguinte URL para se conetar ao StorageGRID:

* `\https://192.0.2.6:10444`


É possível configurar um nome DNS para o endereço IP que os clientes usam para se conetar ao StorageGRID. Contacte o administrador da rede local.

.Passos
. Faça login no Gerenciador de Grade usando um xref:../admin/web-browser-requirements.adoc[navegador da web suportado].
. Para localizar o endereço IP de um nó de grade:
+
.. Selecione *NODES*.
.. Selecione o nó de administração, nó de gateway ou nó de armazenamento ao qual deseja se conetar.
.. Selecione a guia *Visão geral*.
.. Na seção informações do nó, observe os endereços IP do nó.
.. Selecione *Mostrar mais* para visualizar endereços IPv6 e mapeamentos de interface.
+
Você pode estabelecer conexões de aplicativos cliente para qualquer um dos endereços IP na lista:

+
*** *eth0:* rede de Grade
*** *eth1:* Admin Network (opcional)
*** *eth2:* rede de clientes (opcional)
+

NOTE: Se você estiver exibindo um nó de administrador ou um nó de gateway e for o nó ativo em um grupo de alta disponibilidade, o endereço IP virtual do grupo de HA será exibido em eth2.





. Para localizar o endereço IP virtual de um grupo de alta disponibilidade:
+
.. Selecione *CONFIGURATION* > *Network* > *High Availability groups*.
.. Na tabela, anote o endereço IP virtual do grupo HA.


. Para localizar o número da porta de um endpoint do Load Balancer:
+
.. Selecione *CONFIGURATION* > *Network* > *Load balancer endpoints*.
+
A página Load Balancer Endpoints é exibida, mostrando a lista de endpoints que já foram configurados.

.. Selecione um endpoint e selecione *Editar endpoint*.
+
A janela Editar ponto final abre-se e apresenta detalhes adicionais sobre o ponto final.

.. Confirme se o endpoint selecionado está configurado para uso com o protocolo correto (S3 ou Swift) e selecione *Cancelar*.
.. Observe o número da porta do endpoint que você deseja usar para uma conexão de cliente.
+

NOTE: Se o número da porta for 80 ou 443, o endpoint será configurado apenas em nós de Gateway, uma vez que essas portas estão reservadas em nós de administração. Todas as outras portas são configuradas nos nós de Gateway e nos de Admin.




