---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: Você pode usar a solicitação S3 GET Object para recuperar um objeto de um bucket do S3. 
---
= Objeto GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a solicitação S3 GET Object para recuperar um objeto de um bucket do S3.



== OBTER objetos e multipartes

Você pode usar o `partNumber` parâmetro Request para recuperar uma parte específica de um objeto multipart ou segmentado. O `x-amz-mp-parts-count` elemento de resposta indica quantas partes o objeto tem.

Você pode definir `partNumber` como 1 para objetos segmentados/multipartes e objetos não segmentados/não multipartes; no entanto, o `x-amz-mp-parts-count` elemento de resposta é retornado apenas para objetos segmentados ou multipartes.



== Cabeçalhos de solicitação para criptografia no lado do servidor com chaves de criptografia fornecidas pelo cliente (SSE-C)

Use todos os três cabeçalhos se o objeto for criptografado com uma chave exclusiva que você forneceu.

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
* `x-amz-server-side-encryption-customer-key`: Especifique sua chave de criptografia para o objeto.
* `x-amz-server-side-encryption-customer-key-MD5`: Especifique o resumo MD5 da chave de criptografia do objeto.



IMPORTANT: As chaves de criptografia que você fornece nunca são armazenadas. Se você perder uma chave de criptografia, perderá o objeto correspondente. Antes de usar chaves fornecidas pelo cliente para proteger os dados do objeto, revise as considerações em "usar criptografia do lado do servidor".



== UTF-8 carateres em metadados do usuário

O StorageGRID não analisa nem interpreta carateres UTF-8 escapados em metadados definidos pelo usuário. Obter solicitações para um objeto com carateres UTF-8 escapados em metadados definidos pelo usuário não retornam o `x-amz-missing-meta` cabeçalho se o nome ou valor da chave incluir carateres não imprimíveis.



== Cabeçalho de pedido não suportado

O seguinte cabeçalho de solicitação não é suportado e retorna `XNotImplemented`:

* `x-amz-website-redirect-location`




== Controle de versão

Se um `versionId` sub-recurso não for especificado, a operação busca a versão mais recente do objeto em um bucket com versão. Se a versão atual do objeto for um marcador de exclusão, um status "não encontrado" será retornado com o `x-amz-delete-marker` cabeçalho de resposta definido como `true`.



== Comportamento DO GET Object para objetos Pool de storage de nuvem

Se um objeto tiver sido armazenado em um pool de armazenamento em nuvem (consulte as instruções para gerenciar objetos com gerenciamento do ciclo de vida das informações), o comportamento de uma SOLICITAÇÃO GET Object depende do estado do objeto. Consulte "Objeto PRINCIPAL" para obter mais detalhes.


NOTE: Se um objeto for armazenado em um pool de armazenamento em nuvem e uma ou mais cópias do objeto também existirem na grade, as SOLICITAÇÕES DE OBTENÇÃO de objetos tentarão recuperar dados da grade, antes de recuperá-los do pool de armazenamento em nuvem.

|===
| Estado do objeto | Comportamento de GET Object 


 a| 
Objeto ingerido no StorageGRID, mas ainda não avaliado pelo ILM, ou objeto armazenado em um pool de storage tradicional ou usando codificação de apagamento
 a| 
`200 OK`

Uma cópia do objeto é recuperada.



 a| 
Objeto no Cloud Storage Pool, mas ainda não transicionado para um estado não recuperável
 a| 
`200 OK`

Uma cópia do objeto é recuperada.



 a| 
Objeto transicionado para um estado não recuperável
 a| 
`403 Forbidden`, `InvalidObjectState`

Use uma solicitação de restauração PÓS-objeto para restaurar o objeto para um estado recuperável.



 a| 
Objeto em processo de restauração a partir de um estado não recuperável
 a| 
`403 Forbidden`, `InvalidObjectState`

Aguarde até que a solicitação de restauração PÓS-objeto seja concluída.



 a| 
Objeto totalmente restaurado para o Cloud Storage Pool
 a| 
`200 OK`

Uma cópia do objeto é recuperada.

|===


== Objetos segmentados ou multiparte em um pool de armazenamento em nuvem

Se você carregou um objeto multipart ou se o StorageGRID dividir um objeto grande em segmentos, o StorageGRID determina se o objeto está disponível no pool de armazenamento em nuvem amostrando um subconjunto das partes ou segmentos do objeto. Em alguns casos, uma solicitação GET Object pode retornar incorretamente `200 OK` quando algumas partes do objeto já tiverem sido transferidas para um estado não recuperável ou quando algumas partes do objeto ainda não tiverem sido restauradas.

Nestes casos:

* A solicitação GET Object pode retornar alguns dados, mas parar no meio da transferência.
* Uma solicitação OBTER Objeto subsequente pode retornar `403 Forbidden`.


.Informações relacionadas
xref:using-server-side-encryption.adoc[Use a criptografia do lado do servidor]

xref:../ilm/index.adoc[Gerenciar objetos com ILM]

xref:post-object-restore.adoc[Restauração PÓS-objeto]

xref:s3-operations-tracked-in-audit-logs.adoc[S3 operações rastreadas em logs de auditoria]
