---
permalink: s3/operations-on-the-service.html 
sidebar: sidebar 
keywords: operations, service, operations on the service 
summary: O sistema StorageGRID suporta operações no serviço. 
---
= Operações no serviço
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema StorageGRID suporta as seguintes operações no serviço.

|===
| Operação | Implementação 


 a| 
Serviço GET
 a| 
Implementado com todo o comportamento da API REST do Amazon S3.



 a| 
OBTER uso de armazenamento
 a| 
A solicitação OBTER uso do armazenamento informa a quantidade total de armazenamento em uso por uma conta e para cada bucket associado à conta. Esta é uma operação no serviço com um caminho de / e um parâmetro de consulta personalizado (`?x-ntap-sg-usage`) adicionado.



 a| 
OPÇÕES /
 a| 
Os aplicativos clientes podem emitir `OPTIONS /` solicitações para a porta S3 em um nó de storage, sem fornecer credenciais de autenticação S3.1X, para determinar se o nó de storage está disponível. Você pode usar essa solicitação para monitoramento ou permitir que balanceadores de carga externos identifiquem quando um nó de storage está inativo.

|===
.Informações relacionadas
xref:get-storage-usage-request.adoc[OBTER solicitação de uso de armazenamento]
