---
permalink: s3/use-s3-object-lock-default-bucket-retention.html 
sidebar: sidebar 
keywords: s3 object lock, default bucket retention 
summary: Se um bucket tiver o bloqueio de objetos S3 ativado, você poderá especificar um modo de retenção padrão e um período de retenção padrão que é aplicado a cada objeto adicionado ao bucket. 
---
= Use retenção padrão do bucket do bloqueio de objetos S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um bucket tiver o bloqueio de objetos S3 ativado, você poderá especificar um modo de retenção padrão e um período de retenção padrão que é aplicado a cada objeto adicionado ao bucket.

* S3 o bloqueio de objetos pode ser ativado ou desativado para um balde durante a criação do balde.
* Se o bloqueio de objetos S3 estiver ativado para um bucket, você poderá configurar a retenção padrão para o bucket.
* A configuração de retenção padrão especifica:
+
** Modo de retenção padrão: O StorageGRID suporta apenas o modo de "CONFORMIDADE".
** Período de retenção padrão em dias ou anos.






== OBTER Configuração bloqueio Objeto

A solicitação DE configuração GET Object Lock permite determinar se o Object Lock está habilitado para um bucket e, se ele está ativado, ver se há um modo de retenção padrão e período de retenção configurados para o bucket.

Quando novas versões de objetos são ingeridas para o bucket, o modo de retenção padrão é aplicado se `x-amz-object-lock-mode` não for especificado. O período de retenção padrão é usado para calcular a data de retenção até se `x-amz-object-lock-retain-until-date` não for especificado.

Você deve ter a permissão S3:GetBucketObjectLockConfiguration, ou ser raiz da conta, para concluir esta operação.



=== Exemplo de solicitação

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?object-lock HTTP/1.1
Host: _host_
Accept-Encoding: identity
User-Agent: aws-cli/1.18.106 Python/3.8.2 Linux/4.4.0-18362-Microsoft botocore/1.17.29
x-amz-date: _date_
x-amz-content-sha256: _authorization string_
Authorization: _authorization string_
----


=== Exemplo de resposta

[listing]
----
HTTP/1.1 200 OK
x-amz-id-2: iVmcB7OXXJRkRH1FiVq1151/T24gRfpwpuZrEG11Bb9ImOMAAe98oxSpXlknabA0LTvBYJpSIXk=
x-amz-request-id: B34E94CACB2CEF6D
Date: Fri, 04 Sep 2020 22:47:09 GMT
Transfer-Encoding: chunked
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
<ObjectLockConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <ObjectLockEnabled>Enabled</ObjectLockEnabled>
    <Rule>
        <DefaultRetention>
            <Mode>COMPLIANCE</Mode>
            <Years>6</Years>
        </DefaultRetention>
    </Rule>
</ObjectLockConfiguration>
----


== COLOCAR Configuração bloqueio Objeto

A solicitação de configuração de bloqueio de objeto PUT permite modificar o modo de retenção padrão e o período de retenção padrão para um bucket que tem bloqueio de objeto ativado. Você também pode remover as configurações de retenção padrão configuradas anteriormente.

Quando novas versões de objetos são ingeridas para o bucket, o modo de retenção padrão é aplicado se `x-amz-object-lock-mode` não for especificado. O período de retenção padrão é usado para calcular a data de retenção até se `x-amz-object-lock-retain-until-date` não for especificado.

Se o período de retenção padrão for modificado após a ingestão de uma versão de objeto, a data de retenção até a versão do objeto permanecerá a mesma e não será recalculada usando o novo período de retenção padrão.

Você deve ter a permissão S3:PutBucketObjectLockConfiguration, ou ser raiz da conta, para concluir esta operação.

O `Content-MD5` cabeçalho da solicitação deve ser especificado na solicitação DE COLOCAÇÃO.



=== Exemplo de solicitação

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?object-lock HTTP/1.1
Accept-Encoding: identity
Content-Length: 308
Host: _host_
Content-MD5: _request header_
User-Agent: s3sign/1.0.0 requests/2.24.0 python/3.8.2
X-Amz-Date: _date_
X-Amz-Content-SHA256: _authorization string_
Authorization: _authorization string_

<ObjectLockConfiguration>
    <ObjectLockEnabled>Enabled</ObjectLockEnabled>
    <Rule>
        <DefaultRetention>
            <Mode>COMPLIANCE</Mode>
            <Years>6</Years>
        </DefaultRetention>
    </Rule>
</ObjectLockConfiguration>
----