---
permalink: monitor/commonly-used-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, Prometheus metrics, metrics 
summary: O serviço Prometheus nos Admin Nodes coleta métricas de séries temporais dos serviços em todos os nós. Enquanto Prometheus coleta mais de mil métricas, um número relativamente pequeno é necessário para monitorar as operações mais críticas do StorageGRID. 
---
= Métricas de Prometheus comumente usadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O serviço Prometheus nos Admin Nodes coleta métricas de séries temporais dos serviços em todos os nós. Enquanto Prometheus coleta mais de mil métricas, um número relativamente pequeno é necessário para monitorar as operações mais críticas do StorageGRID.

As métricas são armazenadas em cada nó Admin até que o espaço reservado para os dados Prometheus esteja cheio. Quando o `/var/local/mysql_ibdata/` volume atinge a capacidade, as métricas mais antigas são excluídas primeiro.

Para obter a lista completa de métricas, use a API Grid Management.

. Na parte superior do Gerenciador de Grade, selecione o ícone de ajuda e selecione *Documentação da API*.
. Localize as operações *metrics*.
. Execute a `GET /grid/metric-names` operação.
. Faça o download dos resultados.


A tabela a seguir lista as métricas mais usadas do Prometheus. Você pode consultar esta lista para entender melhor as condições nas regras de alerta padrão ou para construir as condições para regras de alerta personalizadas.


NOTE: As métricas que incluem _private_ em seus nomes são destinadas apenas para uso interno e estão sujeitas a alterações entre as versões do StorageGRID sem aviso prévio.

|===
| Métrica Prometheus | Descrição 


 a| 
alertmanager_notifications_failed_total
 a| 
O número total de notificações de alerta com falha.



 a| 
node_filesystem_avail_bytes
 a| 
A quantidade de espaço de sistema de arquivos disponível para usuários não-root em bytes.



 a| 
Node_Memory_MemAvailable_bytes
 a| 
Campo de informações de memória MemAvailable_bytes.



 a| 
node_network_carrier
 a| 
Valor do transportador de /sys/class/net/iface.



 a| 
node_network_receive_errs_total
 a| 
Estatísticas do dispositivo de rede Receive_errs.



 a| 
node_network_transmit_errs_total
 a| 
Estatísticas do dispositivo de rede transmit_errs.



 a| 
StorageGRID_administrativamente_down
 a| 
O nó não está conetado à grade por um motivo esperado. Por exemplo, o nó, ou serviços no nó, foi desligado graciosamente, o nó está reiniciando ou o software está sendo atualizado.



 a| 
StorageGRID_appliance_compute_controller_hardware_status
 a| 
O status do hardware do controlador de computação em um dispositivo.



 a| 
StorageGRID_appliance_failed_disks
 a| 
Para o controlador de armazenamento em um dispositivo, o número de unidades que não são ideais.



 a| 
StorageGRID_appliance_storage_controller_hardware_status
 a| 
O status geral do hardware do controlador de storage em um dispositivo.



 a| 
StorageGRID_content_buckets_and_containers
 a| 
O número total de buckets S3 e contentores Swift conhecidos por este nó de armazenamento.



 a| 
StorageGRID_content_objects
 a| 
O número total de objetos de dados S3 e Swift conhecido por este nó de storage. A contagem é válida apenas para objetos de dados criados por aplicativos clientes que fazem interface com o sistema através de S3 ou Swift.



 a| 
StorageGRID_content_objects_lost
 a| 
O número total de objetos que este serviço deteta como ausentes no sistema StorageGRID. Devem ser tomadas medidas para determinar a causa da perda e se a recuperação é possível.

xref:troubleshooting-lost-and-missing-object-data.adoc[Solucionar problemas de dados de objetos perdidos e ausentes]



 a| 
StorageGRID_http_sessions_incoming_tented
 a| 
O número total de sessões HTTP que foram tentadas para um nó de armazenamento.



 a| 
StorageGRID_http_sessions_incoming_currently_established
 a| 
O número de sessões HTTP que estão atualmente ativas (abertas) no nó de armazenamento.



 a| 
StorageGRID_http_sessions_incoming_failed
 a| 
O número total de sessões HTTP que não foram concluídas com êxito, seja devido a uma solicitação HTTP mal formada ou a uma falha durante o processamento de uma operação.



 a| 
StorageGRID_http_sessions_incoming_successful
 a| 
O número total de sessões HTTP concluídas com êxito.



 a| 
StorageGRID_ilm_awaiting_background_objects
 a| 
O número total de objetos neste nó aguardando avaliação ILM da digitalização.



 a| 
StorageGRID_ilm_awaiting_client_evaluation_objects_per_second
 a| 
A taxa atual na qual os objetos são avaliados em relação à política ILM neste nó.



 a| 
StorageGRID_ilm_awaiting_client_objects
 a| 
O número total de objetos neste nó aguardando avaliação ILM das operações do cliente (por exemplo, ingest).



 a| 
StorageGRID_ilm_awaiting_total_objects
 a| 
O número total de objetos aguardando avaliação ILM.



 a| 
StorageGRID_ilm_scan_objects_per_second
 a| 
A taxa na qual os objetos pertencentes a este nó são digitalizados e enfileirados para o ILM.



 a| 
StorageGRID_ilm_scan_period_estimated_minutes
 a| 
O tempo estimado para concluir uma verificação completa do ILM neste nó.

*Nota:* Uma verificação completa não garante que o ILM tenha sido aplicado a todos os objetos pertencentes a este nó.



 a| 
StorageGRID_load_balancer_endpoint_cert_expiry_time
 a| 
O tempo de expiração do certificado do ponto de extremidade do balanceador de carga em segundos desde a época.



 a| 
StorageGRID_metadata_queries_average_latency_milésimos de segundo
 a| 
O tempo médio necessário para executar uma consulta contra o armazenamento de metadados através deste serviço.



 a| 
StorageGRID_network_received_bytes
 a| 
A quantidade total de dados recebidos desde a instalação.



 a| 
StorageGRID_network_transmitted_bytes
 a| 
A quantidade total de dados enviados desde a instalação.



 a| 
StorageGRID_node_cpu_utilization_percentage
 a| 
A porcentagem de tempo de CPU disponível atualmente sendo usado por este serviço. Indica o quão ocupado o serviço está. A quantidade de tempo de CPU disponível depende do número de CPUs para o servidor.



 a| 
StorageGRID_ntp_chosen_time_source_offset_milissegundos
 a| 
Deslocamento sistemático do tempo fornecido por uma fonte de tempo escolhida. O deslocamento é introduzido quando o atraso para alcançar uma fonte de tempo não é igual ao tempo necessário para que a fonte de tempo alcance o cliente NTP.



 a| 
StorageGRID_ntp_locked
 a| 
O nó não está bloqueado para um servidor NTP (Network Time Protocol).



 a| 
storagegrid_s3_data_transfers_bytes_ingested
 a| 
A quantidade total de dados ingerida de S3 clientes para este nó de armazenamento desde a última reposição do atributo.



 a| 
storagegrid_s3_data_transfers_bytes_retrieved
 a| 
A quantidade total de dados recuperados por clientes S3 a partir deste nó de armazenamento desde que o atributo foi redefinido pela última vez.



 a| 
storagegrid_s3_operations_failed
 a| 
O número total de operações S3 falhadas (códigos de status HTTP 4xx e 5xx), excluindo aquelas causadas por falha de autorização do S3.



 a| 
storagegrid_s3_operations_successful
 a| 
O número total de operações S3 bem-sucedidas (código de status HTTP 2xx).



 a| 
storagegrid_s3_operations_unauthorized
 a| 
O número total de operações S3 falhadas que resultam de uma falha de autorização.



 a| 
StorageGRID_servercertificate_management_interface_cert_expiry_days
 a| 
O número de dias antes do certificado da Interface de Gerenciamento expirar.



 a| 
StorageGRID_servercertificate_storage_api_endpoints_cert_expiry_days
 a| 
O número de dias antes do certificado da API de armazenamento de objetos expirar.



 a| 
StorageGRID_service_cpu_seconds
 a| 
O período de tempo acumulado em que a CPU foi utilizada por este serviço desde a instalação.



 a| 
StorageGRID_service_memory_usage_bytes
 a| 
A quantidade de memória (RAM) atualmente em uso por este serviço. Esse valor é idêntico ao exibido pelo utilitário superior do Linux como RES.



 a| 
StorageGRID_service_network_received_bytes
 a| 
A quantidade total de dados recebidos por este serviço desde a instalação.



 a| 
StorageGRID_service_network_transmitted_bytes
 a| 
A quantidade total de dados enviados por este serviço.



 a| 
StorageGRID_service_restarts
 a| 
O número total de vezes que o serviço foi reiniciado.



 a| 
StorageGRID_service_runtime_seconds
 a| 
O tempo total em que o serviço foi executado desde a instalação.



 a| 
StorageGRID_service_uptime_seconds
 a| 
O tempo total em que o serviço foi executado desde que foi reiniciado pela última vez.



 a| 
StorageGRID_storage_state_current
 a| 
O estado atual dos serviços de storage. Os valores de atributo são:

* 10: Offline
* 15: Manutenção
* 20 - somente leitura
* 30 - Online




 a| 
StorageGRID_storage_status
 a| 
O status atual dos serviços de storage. Os valores de atributo são:

* 0: Sem erros
* 10: Em transição
* 20: Espaço livre insuficiente
* 30 volume(s) indisponível(s)
* 40 - erro




 a| 
StorageGRID_storage_utilization_bytes
 a| 
Uma estimativa do tamanho total dos dados de objetos codificados de apagamento e replicados no nó de storage.



 a| 
StorageGRID_storage_utilization_metadata_allowed_bytes
 a| 
O espaço total no volume 0 de cada nó de storage permitido para metadados de objetos. Esse valor é sempre menor que o espaço real reservado para metadados em um nó, porque uma parte do espaço reservado é necessária para operações essenciais de banco de dados (como compactação e reparo) e futuras atualizações de hardware e software. O espaço permitido para metadados de objetos controla a capacidade geral do objeto.



 a| 
StorageGRID_storage_utilization_metadata_bytes
 a| 
A quantidade de metadados de objetos no volume de armazenamento 0, em bytes.



 a| 
StorageGRID_storage_utilization_total_space_bytes
 a| 
A quantidade total de espaço de armazenamento alocado a todos os armazenamentos de objetos.



 a| 
StorageGRID_storage_utilization_usable_space_bytes
 a| 
A quantidade total de espaço de armazenamento de objetos restante. Calculado adicionando a quantidade de espaço disponível para todos os armazenamentos de objetos no nó de armazenamento.



 a| 
StorageGRID_swift_data_transfers_bytes_ingerido
 a| 
A quantidade total de dados ingerida de clientes Swift para este nó de armazenamento desde que o atributo foi redefinido pela última vez.



 a| 
StorageGRID_swift_data_transfers_bytes_recuperados
 a| 
A quantidade total de dados recuperados pelos clientes Swift deste nó de armazenamento desde que o atributo foi redefinido pela última vez.



 a| 
StorageGRID_swift_operations_failed
 a| 
O número total de operações Swift falhadas (códigos de status HTTP 4xx e 5xx), excluindo as causadas por falha de autorização Swift.



 a| 
StorageGRID_swift_operations_successful
 a| 
O número total de operações Swift bem-sucedidas (código de status HTTP 2xx).



 a| 
StorageGRID_swift_operations_unauthorized
 a| 
O número total de operações Swift falhadas que são o resultado de uma falha de autorização (códigos de status HTTP 401, 403, 405).



 a| 
StorageGRID_tenant_usage_data_bytes
 a| 
O tamanho lógico de todos os objetos para o locatário.



 a| 
StorageGRID_tenant_use_object_count
 a| 
O número de objetos para o inquilino.



 a| 
StorageGRID_tenant_usage_quota_bytes
 a| 
A quantidade máxima de espaço lógico disponível para os objetos do locatário. Se uma métrica de cota não for fornecida, uma quantidade ilimitada de espaço estará disponível.

|===