---
permalink: monitor/comparing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: how to compare alerts and alarms 
summary: Há uma série de semelhanças entre o sistema de alerta e o sistema de alarme legado, mas o sistema de alerta oferece benefícios significativos e é mais fácil de usar. 
---
= Compare alertas e alarmes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há uma série de semelhanças entre o sistema de alerta e o sistema de alarme legado, mas o sistema de alerta oferece benefícios significativos e é mais fácil de usar.

Consulte a tabela a seguir para saber como executar operações semelhantes.

[cols="1a,1a,1a"]
|===
|  | Alertas | Alarmes (sistema legado) 


 a| 
Como posso ver quais alertas ou alarmes estão ativos?
 a| 
* Selecione o link *Current alerts* (alertas atuais) no Painel de instrumentos.
* Selecione o alerta na página *NÓS* *Visão geral*.
* Selecione *ALERTAS* *current*.


xref:viewing-current-alerts.adoc[Ver alertas atuais]
 a| 
Selecione *SUPORTE* *Alarmes (legacy)* *Alarmes atuais*.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
O que faz com que um alerta ou um alarme seja acionado?
 a| 
Os alertas são acionados quando uma expressão Prometheus em uma regra de alerta é avaliada como verdadeira para a condição e duração específicas do gatilho.

xref:view-alert-rules.adoc[Ver regras de alerta]
 a| 
Os alarmes são acionados quando um atributo StorageGRID atinge um valor limite.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Se um alerta ou alarme for acionado, como resolvo o problema subjacente?
 a| 
As ações recomendadas para um alerta estão incluídas nas notificações por e-mail e estão disponíveis nas páginas Alertas no Gerenciador de Grade.

Conforme necessário, informações adicionais são fornecidas na documentação do StorageGRID.

xref:alerts-reference.adoc[Referência de alertas]
 a| 
Você pode aprender sobre um alarme selecionando o nome do atributo ou pode procurar um código de alarme na documentação do StorageGRID.

xref:alarms-reference.adoc[Referência de alarmes (sistema legado)]



 a| 
Onde posso ver uma lista de alertas ou alarmes que foram resolvidos?
 a| 
Selecione *ALERTAS* *resolvidos*.

xref:viewing-resolved-alerts.adoc[Exibir alertas resolvidos]
 a| 
Selecione *SUPORTE* *Alarmes (legado)* *Alarmes históricos*.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Onde posso gerir as definições?
 a| 
Selecione *ALERTAS* *regras*.

xref:managing-alerts.adoc[Gerenciar alertas]
 a| 
Selecione *SUPPORT*. Em seguida, use as opções na seção *Alarmes (legacy)* do menu.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Quais permissões do grupo de usuários eu preciso?
 a| 
* Qualquer pessoa que possa entrar no Gerenciador de Grade pode exibir alertas atuais e resolvidos.
* Você deve ter a permissão Gerenciar Alertas para gerenciar silêncios, notificações de alerta e regras de alerta.


xref:../admin/index.adoc[Administrar o StorageGRID]
 a| 
* Qualquer pessoa que possa entrar no Gerenciador de Grade pode exibir alarmes legados.
* Você deve ter a permissão reconhecer alarmes para reconhecer alarmes.
* Você deve ter as permissões Configuração da Página de topologia de Grade e outras permissões de Configuração de Grade para gerenciar alarmes globais e notificações por e-mail.


xref:../admin/index.adoc[Administrar o StorageGRID]



 a| 
Como faço para gerenciar notificações por e-mail?
 a| 
Selecione *ALERTAS* *Configuração do e-mail*.

*Nota:* como os alarmes e alertas são sistemas independentes, a configuração de e-mail usada para notificações de alarme e AutoSupport não é usada para notificações de alerta. No entanto, você pode usar o mesmo servidor de e-mail para todas as notificações.

xref:email-alert-notifications.adoc[Configurar notificações por e-mail para alertas]
 a| 
Selecione *SUPPORT* *Alarmes (legacy)* *Configuração de e-mail legado*.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Como faço para gerenciar notificações SNMP?
 a| 
Selecione *CONFIGURATION* *Monitoring* *SNMP Agent*.

xref:using-snmp-monitoring.adoc[Utilize a monitorização SNMP]
 a| 
Selecione *CONFIGURATION* *Monitoring* *SNMP Agent*.

xref:using-snmp-monitoring.adoc[Utilize a monitorização SNMP]

*Nota*: As notificações SNMP não são enviadas para cada alarme ou gravidade do alarme.

xref:alarms-that-generate-snmp-notifications.adoc[Alarmes que geram notificações SNMP (sistema legado)]



 a| 
Como posso controlar quem recebe notificações?
 a| 
. Selecione *ALERTAS* *Configuração do e-mail*.
. Na seção *destinatários*, insira um endereço de e-mail para cada lista de e-mail ou pessoa que deve receber um e-mail quando ocorrer um alerta.


xref:email-alert-notifications.adoc[Configurar notificações por e-mail para alertas]
 a| 
. Selecione *SUPPORT* *Alarmes (legacy)* *Configuração de e-mail legado*.
. Criando uma lista de discussão.
. Selecione *notificações*.
. Selecione a lista de discussão.


xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Quais nós de administrador enviam notificações?
 a| 
Um único nó Admin (o "'remetente preferido'").

xref:../admin/index.adoc[Administrar o StorageGRID]
 a| 
Um único nó Admin (o "'remetente preferido'").

xref:../admin/index.adoc[Administrar o StorageGRID]



 a| 
Como faço para suprimir algumas notificações?
 a| 
. Selecione *ALERTAS* *silêncios*.
. Selecione a regra de alerta que deseja silenciar.
. Especifique uma duração para o silêncio.
. Selecione a gravidade do alerta que deseja silenciar.
. Selecione para aplicar o silêncio a toda a grade, a um único local ou a um único nó.


*Nota*: Se você ativou o agente SNMP, os silêncios também suprimem traps SNMP e informam.

xref:silencing-alert-notifications.adoc[Silenciar notificações de alerta]
 a| 
. Selecione *SUPPORT* *Alarmes (legacy)* *Configuração de e-mail legado*.
. Selecione *notificações*.
. Selecione uma lista de discussão e selecione *suprimir*.


xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Como faço para suprimir todas as notificações?
 a| 
Selecione *ALERTAS* *silêncios*.em seguida, selecione *todas as regras*.

*Nota*: Se você ativou o agente SNMP, os silêncios também suprimem traps SNMP e informam.

xref:silencing-alert-notifications.adoc[Silenciar notificações de alerta]
 a| 
. Selecione *CONFIGURATION* > *System* > *Display OPTIONS*.
. Marque a caixa de seleção *notificação suprimir tudo*.


*Nota*: A supressão de notificações por e-mail em todo o sistema também suprime os e-mails do AutoSupport acionados por eventos.

xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Como posso personalizar as condições e os gatilhos?
 a| 
. Selecione *ALERTAS* *regras*.
. Selecione uma regra padrão para editar ou selecione *criar regra personalizada*.


xref:editing-alert-rules.adoc[Editar regras de alerta]

xref:creating-custom-alert-rules.adoc[Crie regras de alerta personalizadas]
 a| 
. Selecione *SUPORTE* *Alarmes (legado)* *Alarmes globais*.
. Crie um alarme personalizado global para substituir um alarme padrão ou para monitorar um atributo que não tenha um alarme padrão.


xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]



 a| 
Como posso desativar um alerta individual ou um alarme?
 a| 
. Selecione *ALERTAS* *regras*.
. Selecione a regra e selecione *Editar regra*.
. Desmarque a caixa de seleção *Enabled*.


xref:disabling-alert-rules.adoc[Desativar regras de alerta]
 a| 
. Selecione *SUPORTE* *Alarmes (legado)* *Alarmes globais*.
. Selecione a regra e selecione o ícone Editar.
. Desmarque a caixa de seleção *Enabled*.


xref:managing-alarms.adoc[Gerenciar alarmes (sistema legado)]

|===