---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente uma mensagem AutoSupport a ser enviada. 
---
= Acione manualmente uma mensagem AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente uma mensagem AutoSupport a ser enviada.

.O que você vai precisar
* Você deve estar conetado ao Gerenciador de Grade usando um xref:../admin/web-browser-requirements.adoc[navegador da web suportado].
* Você deve ter a permissão de Acesso root ou outra Configuração de Grade.


.Passos
. Selecione *SUPPORT* > *Tools* > *AutoSupport*.
+
A página AutoSupport é exibida com a guia *Configurações* selecionada.

. Selecione *Enviar AutoSupport acionado pelo usuário*.
+
O StorageGRID tenta enviar uma mensagem do AutoSupport para o suporte técnico. Se a tentativa for bem-sucedida, os valores *resultado mais recente* e *último tempo bem-sucedido* na guia *resultados* serão atualizados. Se houver um problema, o valor *resultado mais recente* será atualizado para "Falha" e o StorageGRID não tentará enviar a mensagem AutoSupport novamente.

+

NOTE: Depois de enviar uma mensagem AutoSupport acionada pelo usuário, atualize a página AutoSupport no seu navegador após 1 minuto para acessar os resultados mais recentes.



.Informações relacionadas
xref:managing-alarms.adoc[Configurar as definições do servidor de correio eletrónico para alarmes (sistema legado)]
