---
permalink: maintain/fixing-missing-block-device-errors.html 
sidebar: sidebar 
keywords: storagegrid, missing block device, block device error 
summary: 'O sistema verifica se cada nó recuperado mapeia para um arquivo especial válido de dispositivo de bloco ou um softlink válido para um arquivo especial de dispositivo de bloco. Se o StorageGRID encontrar mapeamento inválido no `/etc/storagegrid/nodes/_node-name_.conf` arquivo, um erro de dispositivo de bloco ausente será exibido.' 
---
= Corrigir erros de dispositivo de bloco em falta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema verifica se cada nó recuperado mapeia para um arquivo especial válido de dispositivo de bloco ou um softlink válido para um arquivo especial de dispositivo de bloco. Se o StorageGRID encontrar mapeamento inválido no `/etc/storagegrid/nodes/_node-name_.conf` arquivo, um erro de dispositivo de bloco ausente será exibido.

Se observar um erro correspondente a este padrão:

`Checking configuration file /etc/storagegrid/nodes/_node-name_.conf for node _node-name_...`
`ERROR: _node-name_: BLOCK_DEVICE_PURPOSE = _path-name_` _node-name_: _path-name_ não existe

Isso significa que `/etc/storagegrid/nodes/_node-name_.conf` mapeia o dispositivo de bloco usado por _node-name_ para FINS para o caminho-nome dado no sistema de arquivos Linux, mas não há um arquivo especial válido de dispositivo de bloco ou softlink para um arquivo especial de dispositivo de bloco, nesse local.

Verifique se você concluiu as etapas em xref:deploying-new-linux-hosts.adoc[Implante novos hosts Linux]. Use os mesmos nomes de dispositivos persistentes para todos os dispositivos de bloco que foram usados no host original.

Se você não conseguir restaurar ou recriar o arquivo especial de dispositivo de bloco ausente, você pode alocar um novo dispositivo de bloco com o tamanho e categoria de armazenamento apropriados e editar o arquivo de configuração de nó para alterar o valor de block_DEVICE_PURPOSE para apontar para o novo arquivo especial de dispositivo de bloco.

Determine o tamanho e a categoria de armazenamento apropriados nas tabelas na seção "requisitos de armazenamento" das instruções de instalação do seu sistema operacional Linux. Revise as recomendações em ""Configurando o armazenamento do host"" antes de prosseguir com a substituição do dispositivo de bloco.


IMPORTANT: Se você precisar fornecer um novo dispositivo de armazenamento de bloco para qualquer uma das variáveis de arquivo de configuração começando com `BLOCK_DEVICE_` porque o dispositivo de bloco original foi perdido com o host com falha, verifique se o novo dispositivo de bloco está desformatado antes de tentar outros procedimentos de recuperação. O novo dispositivo de bloco será desformatado se você estiver usando armazenamento compartilhado e tiver criado um novo volume. Se você não tiver certeza, execute o seguinte comando contra qualquer novo dispositivo de armazenamento de bloco arquivos especiais.

CUIDADO:

Execute o seguinte comando apenas para novos dispositivos de armazenamento de bloco. Não execute este comando se você acredita que o armazenamento de bloco ainda contém dados válidos para o nó que está sendo recuperado, pois quaisquer dados no dispositivo serão perdidos.

[listing]
----
sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1
----
.Informações relacionadas
xref:../rhel/index.adoc[Instale o Red Hat Enterprise Linux ou CentOS]

xref:../ubuntu/index.adoc[Instale Ubuntu ou Debian]
