---
permalink: maintain/linux-exporting-node-from-source-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, export node, linux source host 
summary: Encerre o nó da grade e exporte-o do host Linux de origem. 
---
= Linux: Nó de exportação do host de origem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encerre o nó da grade e exporte-o do host Linux de origem.

Execute o seguinte comando no host Linux de origem.

. Obtenha o status de todos os nós atualmente em execução no host de origem.
+
[listing]
----
sudo storagegrid node status all
----
+
`Name Config-State Run-State`

+
`DC1-ADM1 Configured Running`

+
`DC1-ARC1 Configured Running`

+
`DC1-GW1 Configured Running`

+
`DC1-S1 Configured Running`

+
`DC1-S2 Configured Running`

+
`DC1-S3 Configured Running`

. Identifique o nome do nó que deseja migrar e pare-o se o estado de execução for `Running`.
+
[listing]
----
sudo storagegrid node stop DC1-S3
----
+
`Stopping node DC1-S3`

+
`Waiting up to 630 seconds for node shutdown`

. Exporte o nó do host de origem.
+
[listing]
----
sudo storagegrid node export DC1-S3
----
+
`Finished exporting node DC1-S3 to /dev/mapper/sgws-dc1-s3-var-local.`

+
`Use 'storagegrid node import /dev/mapper/sgws-dc1-s3-var-local' if you`

+
`want to import it again.`

. Tome nota `import command suggested in the output of the `export` do comando.
+
Você executará esse comando no host de destino na próxima etapa.


