---
permalink: maintain/linux-importing-node-on-target-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, import node, importing node, target host 
summary: Depois de exportar o nó do host de origem, você importa e valida o nó no host Linux de destino. A validação confirma que o nó tem acesso aos mesmos dispositivos de interface de rede e armazenamento de bloco que tinha no host de origem. 
---
= Linux: Importar nó no host de destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de exportar o nó do host de origem, você importa e valida o nó no host Linux de destino. A validação confirma que o nó tem acesso aos mesmos dispositivos de interface de rede e armazenamento de bloco que tinha no host de origem.

Execute o seguinte comando no host Linux de destino.

. Importe o nó no host de destino.
+
[listing]
----
sudo storagegrid node import /dev/mapper/sgws-dc1-s3-var-local
----
+
`Finished importing node DC1-S3 from /dev/mapper/sgws-dc1-s3-var-local.`

+
`You should run 'storagegrid node validate DC1-S3'`

. Valide a configuração do nó no novo host.
+
[listing]
----
sudo storagegrid node validate DC1-S3
----
+
`+Confirming existence of node DC1-S3... PASSED+`

+
`+Checking configuration file /etc/storagegrid/nodes/DC1-S3.conf for node DC1-S3... PASSED+`

+
`+Checking for duplication of unique values... PASSED+`

. Se ocorrerem erros de validação, solucione-os antes de iniciar o nó migrado.
+
Para obter informações sobre solução de problemas, consulte as instruções de instalação do StorageGRID para seu sistema operacional Linux.



.Informações relacionadas
xref:../rhel/index.adoc[Instale o Red Hat Enterprise Linux ou CentOS]

xref:../ubuntu/index.adoc[Instale Ubuntu ou Debian]
