---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node failure 
summary: O procedimento para recuperar um nó de storage com falha depende do tipo de falha e do tipo de nó de storage que falhou. 
---
= Recuperar de falhas no nó de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O procedimento para recuperar um nó de storage com falha depende do tipo de falha e do tipo de nó de storage que falhou.

Use esta tabela para selecionar o procedimento de recuperação para um nó de armazenamento com falha.

[cols="1a,1a,1a"]
|===
| Problema | Ação | Notas 


 a| 
* Mais de um nó de storage falhou.
* Um segundo nó de storage falhou menos de 15 dias após uma falha ou recuperação do nó de storage.
+
Isso inclui o caso em que um nó de storage falha enquanto a recuperação de outro nó de storage ainda está em andamento.


 a| 
Você deve entrar em Contato com o suporte técnico.
 a| 
Se todos os nós de storage com falha estiverem no mesmo local, talvez seja necessário executar um procedimento de recuperação de local.

O suporte técnico avaliará sua situação e desenvolverá um plano de recuperação.

xref:how-site-recovery-is-performed-by-technical-support.adoc[Como a recuperação do local é realizada pelo suporte técnico]

A recuperação de mais de um nó de storage (ou mais de um nó de storage em 15 dias) pode afetar a integridade do banco de dados Cassandra, o que pode causar perda de dados.

O suporte técnico pode determinar quando é seguro iniciar a recuperação de um segundo nó de armazenamento.

*Nota*: Se mais de um nó de armazenamento que contém o serviço ADC falhar em um site, você perderá quaisquer solicitações de serviço de plataforma pendentes para esse site.



 a| 
Um nó de armazenamento está offline há mais de 15 dias.
 a| 
xref:recovering-storage-node-that-has-been-down-more-than-15-days.adoc[Recupere o nó de storage abaixo mais de 15 dias]
 a| 
Este procedimento é necessário para garantir a integridade do banco de dados Cassandra.



 a| 
Um nó de storage de dispositivo falhou.
 a| 
xref:recovering-storagegrid-appliance-storage-node.adoc[Recupere o nó de storage do dispositivo]
 a| 
O procedimento de recuperação para nós de storage do dispositivo é o mesmo para todas as falhas.



 a| 
Um ou mais volumes de armazenamento falharam, mas a unidade do sistema está intacta
 a| 
xref:recovering-from-storage-volume-failure-where-system-drive-is-intact.adoc[Recuperar de uma falha no volume de armazenamento em que a unidade do sistema está intacta]
 a| 
Este procedimento é usado para nós de storage baseados em software.



 a| 
A unidade do sistema falhou.
 a| 
xref:recovering-from-system-drive-failure.adoc[Recuperar de falha na unidade do sistema]
 a| 
O procedimento de substituição do nó depende da plataforma de implantação e se algum volume de storage também falhou.

|===

NOTE: Alguns procedimentos de recuperação do StorageGRID usam o Reaper para lidar com reparos do Cassandra. As reparações ocorrem automaticamente assim que os serviços relacionados ou necessários tiverem sido iniciados. Você pode notar saída de script que menciona "reaper" ou "Cassandra repair." se você vir uma mensagem de erro indicando que o reparo falhou, execute o comando indicado na mensagem de erro.
