---
permalink: maintain/removing-donotstart-file-for-service.html 
sidebar: sidebar 
keywords: storagegrid, recover, donotstart file, do not start file, remove donotstart, removing donotstart, remove do not start, removing do not start 
summary: Quando você remove um arquivo DoNotStart que está impedindo que um serviço seja iniciado, você deve iniciar esse serviço. 
---
= Remova o arquivo DoNotStart para serviço
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você remove um arquivo DoNotStart que está impedindo que um serviço seja iniciado, você deve iniciar esse serviço.

.O que você vai precisar
Tem de ter o `Passwords.txt` ficheiro.

.Passos
. Faça login no nó da grade:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.

. Remova o arquivo DoNotStart do diretório de serviços: `rm /etc/sv/_service_/DoNotStart`
+
 `service`onde está o nome do serviço. Por exemplo,

+
[listing]
----
rm /etc/sv/ldr/DoNotStart
----
. Inicie o serviço: `service _servicename_ start`
. Faça logout do shell de comando: `exit`

