---
permalink: sg5700/gathering-installation-information-sg5700.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: À medida que você instala e configura o dispositivo StorageGRID, você deve tomar decisões e coletar informações sobre portas de switch Ethernet, endereços IP e modos de ligação de porta e rede. 
---
= Reunir informações de instalação (SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À medida que você instala e configura o dispositivo StorageGRID, você deve tomar decisões e coletar informações sobre portas de switch Ethernet, endereços IP e modos de ligação de porta e rede.

.Sobre esta tarefa
Você pode usar as tabelas a seguir para gravar as informações necessárias para cada rede conetada ao aparelho. Esses valores são necessários para instalar e configurar o hardware.



== Informações necessárias para se conetar ao Gerenciador de sistemas SANtricity no controlador E2800

Você deve conetar o controlador E2800 à rede de gerenciamento que você usará para o Gerenciador de sistema do SANtricity.

|===
| Informações necessárias | O seu valor 


 a| 
Porta do switch Ethernet, você se conetará à porta de gerenciamento 1
 a| 



 a| 
Endereço MAC para a porta de gerenciamento 1 (impresso em uma etiqueta próxima à porta P1 para o controlador E2800A e 0a para o controlador E2800B)
 a| 



 a| 
Endereço IP atribuído pelo DHCP para a porta de gerenciamento 1, se disponível após a ativação

*Observação:* se a rede que você se conetará ao controlador E2800 incluir um servidor DHCP, o administrador da rede poderá usar o endereço MAC para determinar o endereço IP atribuído pelo servidor DHCP.
 a| 



 a| 
Velocidade e modo duplex

*Observação:* você deve certificar-se de que o switch Ethernet da rede de gerenciamento do Gerenciador de sistema do SANtricity esteja definido como negociação automática.
 a| 
Deve ser:

* Negociação automática (padrão)




 a| 
Formato do endereço IP
 a| 
Escolha uma:

* IPv4
* IPv6




 a| 
Endereço IP estático que pretende utilizar para o dispositivo na rede de gestão
 a| 
Para IPv4:

* Endereço IPv4:
* Máscara de sub-rede:
* Gateway:


Para IPv6:

* Endereço IPv6:
* Endereço IP roteável:
* Endereço IP do router do controlador E2800:


|===


== Informações necessárias para conetar o controlador E5700SG à rede de administração

A rede de administração para StorageGRID é uma rede opcional, usada para administração e manutenção do sistema. O dispositivo se coneta à rede Admin usando as portas de gerenciamento de 1 GbE no controlador E5700SG.

|===
| Informações necessárias | O seu valor 


 a| 
Rede de administração ativada
 a| 
Escolha uma:

* Não
* Sim (predefinição)




 a| 
Modo de ligação de rede
 a| 
Escolha uma:

* Independente
* Ative-Backup




 a| 
Porta do switch para a porta 1
 a| 



 a| 
Porta do switch para a porta 2 (apenas modo de ligação de rede ative-Backup)
 a| 



 a| 
Endereço IP atribuído pelo DHCP para a porta de gerenciamento 1, se disponível após a ativação

*Observação:* se a rede Admin incluir um servidor DHCP, o controlador E5700SG exibirá o endereço IP atribuído pelo DHCP em sua tela de sete segmentos depois que ele for inicializado. Você também pode determinar o endereço IP atribuído pelo DHCP usando o endereço MAC para procurar o IP atribuído.
 a| 
* Endereço IPv4 (CIDR):
* Gateway:




 a| 
Endereço IP estático que pretende utilizar para o nó de armazenamento do dispositivo na rede de administração

*Nota:* se a rede não tiver um gateway, especifique o mesmo endereço IPv4 estático para o gateway.
 a| 
* Endereço IPv4 (CIDR):
* Gateway:




 a| 
Sub-redes de rede Admin (CIDR)
 a| 

|===


== Informações necessárias para conetar e configurar portas 10/25-GbE no controlador E5700SG

As quatro portas 10/25-GbE no controlador E5700SG conetam-se à rede de Grade StorageGRID e à rede do cliente.


NOTE: Consulte "conexões de porta 10/25-GbE para o controlador E5700SG" para obter mais informações sobre as opções dessas portas.

|===
| Informações necessárias | O seu valor 


 a| 
Velocidade da ligação

*Nota:* se você selecionar 25 GbE, você deve instalar SPF28 transcetores. A negociação automática não é suportada, portanto você também deve configurar as portas e os switches conetados para 25GbE.
 a| 
Escolha uma:

* 10 GbE (padrão)
* 25 GbE




 a| 
Modo de ligação da porta
 a| 
Escolha uma:

* Fixo (padrão)
* Agregado




 a| 
Porta do switch para a porta 1 (rede do cliente)
 a| 



 a| 
Porta do switch para a porta 2 (rede de grade)
 a| 



 a| 
Porta do switch para a porta 3 (rede do cliente)
 a| 



 a| 
Porta do switch para a porta 4 (rede de grade)
 a| 

|===


== Informações necessárias para conetar o controlador E5700SG à rede de Grade

A rede de Grade para StorageGRID é uma rede necessária, usada para todo o tráfego interno de StorageGRID. O dispositivo se coneta à rede de Grade usando as portas 10/25-GbE no controlador E5700SG.


NOTE: Consulte "conexões de porta 10/25-GbE para o controlador E5700SG" para obter mais informações sobre as opções dessas portas.

|===
| Informações necessárias | O seu valor 


 a| 
Modo de ligação de rede
 a| 
Escolha uma:

* Ative-Backup (padrão)
* Bola de Futsal (802,3ad)




 a| 
Marcação de VLAN ativada
 a| 
Escolha uma:

* Não (predefinição)
* Sim




 a| 
Tag VLAN (se a marcação VLAN estiver ativada)
 a| 
Introduza um valor entre 0 e 4095:



 a| 
Endereço IP atribuído pelo DHCP para a rede de Grade, se disponível após a ativação

*Observação:* se a rede de Grade incluir um servidor DHCP, o controlador E5700SG exibirá o endereço IP atribuído pelo DHCP para a rede de Grade em sua tela de sete segmentos após a inicialização.
 a| 
* Endereço IPv4 (CIDR):
* Gateway:




 a| 
Endereço IP estático que pretende utilizar para o nó de armazenamento do dispositivo na rede de grelha

*Nota:* se a rede não tiver um gateway, especifique o mesmo endereço IPv4 estático para o gateway.
 a| 
* Endereço IPv4 (CIDR):
* Gateway:




 a| 
Sub-redes de rede de rede (CIDR)

*Nota:* se a rede do cliente não estiver ativada, a rota padrão no controlador usará o gateway especificado aqui.
 a| 

|===


== Informações necessárias para conetar o controlador E5700SG à rede do cliente

A rede de cliente para StorageGRID é uma rede opcional, normalmente usada para fornecer acesso de protocolo de cliente à grade. O dispositivo se coneta à rede do cliente usando as portas 10/25-GbE no controlador E5700SG.


NOTE: Consulte "conexões de porta 10/25-GbE para o controlador E5700SG" para obter mais informações sobre as opções dessas portas.

|===
| Informações necessárias | O seu valor 


 a| 
Rede cliente ativada
 a| 
Escolha uma:

* Não (predefinição)
* Sim




 a| 
Modo de ligação de rede
 a| 
Escolha uma:

* Ative-Backup (padrão)
* Bola de Futsal (802,3ad)




 a| 
Marcação de VLAN ativada
 a| 
Escolha uma:

* Não (predefinição)
* Sim




 a| 
Etiqueta VLAN

(Se a marcação VLAN estiver ativada)
 a| 
Introduza um valor entre 0 e 4095:



 a| 
Endereço IP atribuído pelo DHCP para a rede do cliente, se disponível após a ligação
 a| 
* Endereço IPv4 (CIDR):
* Gateway:




 a| 
Endereço IP estático que pretende utilizar para o nó de armazenamento do dispositivo na rede do cliente

*Nota:* se a rede do cliente estiver ativada, a rota padrão no controlador usará o gateway especificado aqui.
 a| 
* Endereço IPv4 (CIDR):
* Gateway:


|===
.Informações relacionadas
xref:reviewing-appliance-network-connections-sg5700.adoc[Revisão de conexões de rede de dispositivos (SG5700)]

xref:port-bond-modes-for-e5700sg-controller-ports.adoc[Modos de ligação de porta para E5700SG portas de controlador]

xref:configuring-hardware-sg5712-60.adoc[Configurar hardware (SG5700)]
