---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Um pool de storage é um agrupamento lógico de nós de storage ou nós de arquivamento. Você configura pools de storage para determinar onde o sistema StorageGRID armazena dados de objetos e o tipo de storage usado. 
---
= O que é um pool de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um pool de storage é um agrupamento lógico de nós de storage ou nós de arquivamento. Você configura pools de storage para determinar onde o sistema StorageGRID armazena dados de objetos e o tipo de storage usado.

Os pools de armazenamento têm dois atributos:

* *Storage grade*: Para nós de storage, o desempenho relativo do armazenamento de backup.
* *Site*: O centro de dados onde os objetos serão armazenados.


Os pools de armazenamento são usados em regras ILM para determinar onde os dados do objeto são armazenados. Ao configurar regras de ILM para replicação, você seleciona um ou mais pools de storage que incluem nós de storage ou nós de arquivamento. Ao criar perfis de codificação de apagamento, você seleciona um pool de storage que inclua nós de storage.
