---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, preferred master, backup interface 
summary: Ao configurar o StorageGRID para uso com o FabricPool, você pode, opcionalmente, criar um ou mais grupos de alta disponibilidade. Um grupo de HA consiste em uma ou mais interfaces de rede em nós de administração, nós de gateway ou ambos. 
---
= Criar um grupo de alta disponibilidade (HA) para o FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar o StorageGRID para uso com o FabricPool, você pode, opcionalmente, criar um ou mais grupos de alta disponibilidade (HA). Um grupo de HA consiste em uma ou mais interfaces de rede em nós de administração, nós de gateway ou ambos.

.O que você vai precisar
* Você está conetado ao Gerenciador de Grade usando um xref:../admin/web-browser-requirements.adoc[navegador da web suportado].
* Você tem a permissão de acesso root.
* Se você planeja usar uma VLAN, criou a interface VLAN. xref:../admin/configure-vlan-interfaces.adoc[Configurar interfaces VLAN]Consulte .


.Sobre esta tarefa
Cada grupo de HA usa endereços IP virtuais (VIPs) para fornecer acesso altamente disponível aos serviços compartilhados nos nós associados.

Para obter detalhes sobre esta tarefa, xref:../admin/managing-high-availability-groups.adoc[Gerenciar grupos de alta disponibilidade]consulte .

.Passos
. Selecione *CONFIGURATION* > *Network* > *High Availability groups*.
. Selecione *criar*.
. Insira um nome exclusivo e, opcionalmente, uma descrição.
. Selecione uma ou mais interfaces para adicionar a esse grupo de HA.
+
Use os cabeçalhos de coluna para classificar as linhas ou insira um termo de pesquisa para localizar interfaces mais rapidamente.

. Determine a interface principal e quaisquer interfaces de backup para esse grupo de HA.
+
Arraste e solte linhas para alterar os valores na coluna *Priority Order*.

+
A primeira interface na lista é a interface principal. A interface principal é a interface ativa, a menos que ocorra uma falha.

+
Se o grupo HA incluir mais de uma interface e a interface ativa falhar, os endereços VIP serão movidos para a primeira interface de backup na ordem de prioridade. Se essa interface falhar, os endereços VIP serão movidos para a próxima interface de backup, e assim por diante. Quando as falhas são resolvidas, os endereços VIP voltam para a interface de maior prioridade disponível.

. Especifique a sub-rede VIP na notação CIDR& n.o 8212;um endereço IPv4 seguido de uma barra e o comprimento da sub-rede (0-32).
+
O endereço de rede não deve ter nenhum bit de host definido. Por exemplo, `192.16.0.0/22`.

. Opcionalmente, se os endereços IP do ONTAP usados para acessar o StorageGRID não estiverem na mesma sub-rede que os endereços VIP do StorageGRID, insira o endereço IP do gateway local do StorageGRID VIP. O endereço IP do gateway local deve estar dentro da sub-rede VIP.
. Introduza um ou mais endereços IP virtuais para o grupo HA. Você pode adicionar até 10 endereços IP. Todos os VIPs devem estar dentro da sub-rede VIP.
+
Você deve fornecer pelo menos um endereço IPv4. Opcionalmente, você pode especificar endereços IPv4 e IPv6 adicionais.

. Selecione *Create HA group* e, em seguida, selecione *Finish*.

